function getGameList(index)

table = {
	{ --CAPCOM
	"1942 (PlayChoice-10)",
	"1942 (set 1)",
	"1942 (set 2)",
	"1942 (set 3)",
	"1943 Kai: Midway Kaisen (Japan)",
	"1943: Midway Kaisen (Japan)",
	"1943: The Battle of Midway (US)",
	"Adventure Quiz 2 Hatena Hatena no Dai-Bouken (Japan 900228)",
	"Ares no Tsubasa (Japan)",
	"Avengers (US set 1)",
	"Avengers (US set 2)",
	"Bionic Commando (US set 1)",
	"Bionic Commando (US set 2)",
	"Black Dragon",
	"Black Tiger",
	"Block Block (Japan 910910)",
	"Block Block (World 910910)",
	"Block Block (World 911106 Joystick)",
	"Buster Bros. (US)",
	"Capcom Baseball (Japan)",
	"Capcom World (Japan)",
	"Chip'n Dale: Rescue Rangers (PlayChoice-10)",
	"Commando (US)",
	"Commando (World)",
	"Dokaben (Japan)",
	"Exed Exes",
	"F-1 Dream",
	"Ghosts'n Goblins (US)",
	"Ghosts'n Goblins (World? set 1)",
	"Ghosts'n Goblins (World? set 2)",
	"Ghouls'n Ghosts (Mega-Tech)",
	"Gun.Smoke (Japan)",
	"Gun.Smoke (US set 1)",
	"Gun.Smoke (US set 2)",
	"Gun.Smoke (World)",
	"Hissatsu Buraiken (Japan)",
	"Last Duel (US set 1)",
	"Last Duel (US set 2)",
	"Led Storm (US)",
	"Legendary Wings (US set 1)",
	"Legendary Wings (US set 2)",
	"Mad Gear (Japan)",
	"Mad Gear (US)",
	"Makai-Mura (Japan Revision C)",
	"Makai-Mura (Japan Revision G)",
	"Makai-Mura (Japan)",
	"Mega Man III (PlayChoice-10)",
	"Pirate Ship Higemaru",
	"Quiz Sangokushi (Japan)",
	"Quiz Tonosama no Yabou (Japan)",
	"Rush &amp; Crash (Japan)",
	"Savage Bees",
	"Section Z (set 1)",
	"Section Z (set 2)",
	"Senjou no Ookami",
	"Side Arms - Hyper Dyne (Japan)",
	"Side Arms - Hyper Dyne (US)",
	"Side Arms - Hyper Dyne (World)",
	"Slipstream (bad dump?)",
	"Son Son",
	"Son Son (Japan)",
	"Space Invasion (Europe)",
	"Street Fighter (Japan)",
	"Street Fighter (prototype)",
	"Street Fighter (US)",
	"Street Fighter (World)",
	"Street Fighter: The Movie (v1.10)",
	"Street Fighter: The Movie (v1.11)",
	"Street Fighter: The Movie (v1.12)",
	"Street Fighter: The Movie (v1.12N, Japan)",
	"Tatakai no Banka (Japan)",
	"The Speed Rumbler (set 1)",
	"The Speed Rumbler (set 2)",
	"Tiger Road (US)",
	"Top Secret (Japan)",
	"Tora-he no Michi (Japan)",
	"Trojan (PlayChoice-10)",
	"Trojan (Romstar)",
	"Trojan (US)",
	"Vulgus (Japan?)",
	"Vulgus (set 1)",
	"Vulgus (set 2)",
	"Yo! Noid (PlayChoice-10)",
	},
	{ --CAVE
	"Power Instinct 2 (USA)",
	"Mazinger Z",
	"DonPachi (US)",
	"DonPachi (Japan)",
	"DonPachi (Korea)",
	"Metamoqester",
	"Oni - The Ninja Master (Japan)",
	"Pretty Soldier Sailor Moon (95/03/22B)",
	"Pretty Soldier Sailor Moon (95/03/22)",
	"Air Gallet",
	"Hotdog Storm",
	"DoDonPachi (International)",
	"DoDonPachi (Japan)",
	"Dangun Feveron (Japan)",
	"Fever SOS (International)",
	"ESP Ra.De. (International Ver 1998 4/22)",
	"ESP Ra.De. (Japan Ver 1998 4/21)",
	"ESP Ra.De. (Japan Ver 1998 4/14)",
	"Uo Poko (Japan)",
	"Guwange (Japan)",
	"Gaia Crusaders",
	},
	{ --CPS1
	"Forgotten Worlds (US)",
	"Lost Worlds (Japan)",
	"Ghouls'n Ghosts (World)",
	"Ghouls'n Ghosts (US)",
	"Dai Makai-Mura (Japan)",
	"Strider (US set 1)",
	"Strider (US set 2)",
	"Strider Hiryu (Japan set 1)",
	"Strider Hiryu (Japan set 2)",
	"Willow (US)",
	"Willow (Japan, Japanese)",
	"Willow (Japan, English)",
	"U.N. Squadron (US)",
	"Area 88 (Japan)",
	"Final Fight (World)",
	"Final Fight (US 900112)",
	"Final Fight (Japan)",
	"Final Fight (Japan 900305)",
	"1941 - Counter Attack (World)",
	"1941 - Counter Attack (Japan)",
	"Mercs (World 900302)",
	"Mercs (US 900302)",
	"Mercs (US 900608)",
	"Senjou no Ookami II (Japan 900302)",
	"Mega Twins (World 900619)",
	"Chiki Chiki Boys (Japan 900619)",
	"Magic Sword - Heroic Fantasy (World 900725)",
	"Magic Sword - Heroic Fantasy (World 900623)",
	"Magic Sword - Heroic Fantasy (US 900725)",
	"Magic Sword (Japan 900623)",
	"Carrier Air Wing (World 901012)",
	"Carrier Air Wing (US 901012)",
	"U.S. Navy (Japan 901012)",
	"Nemo (World 901130)",
	"Nemo (Japan 901120)",
	"Street Fighter II - The World Warrior (World 910522)",
	"Street Fighter II - The World Warrior (World 910214)",
	"Street Fighter II - The World Warrior (US 910206)",
	"Street Fighter II - The World Warrior (US 910214)",
	"Street Fighter II - The World Warrior (US 910318)",
	"Street Fighter II - The World Warrior (US 910228)",
	"Street Fighter II - The World Warrior (US 910411)",
	"Street Fighter II - The World Warrior (US 910522)",
	"Street Fighter II - The World Warrior (US 911101)",
	"Street Fighter II - The World Warrior (Japan 911210)",
	"Street Fighter II - The World Warrior (Japan 910214)",
	"Street Fighter II - The World Warrior (Japan 910306)",
	"Three Wonders (World 910520)",
	"Three Wonders (US 910520)",
	"Wonder 3 (Japan 910520)",
	"The King of Dragons (World 910711)",
	"The King of Dragons (US 910910)",
	"The King of Dragons (Japan 910805)",
	"The King of Dragons (bootleg)",
	"Captain Commando (World 911014)",
	"Captain Commando (US 910928)",
	"Captain Commando (Japan 911202)",
	"Knights of the Round (World 911127)",
	"Knights of the Round (US 911127)",
	"Knights of the Round (Japan 911127)",
	"Street Fighter II' - Champion Edition (World 920313)",
	"Street Fighter II' - Champion Edition (US 920313)",
	"Street Fighter II' - Champion Edition (US 920513)",
	"Street Fighter II' - Champion Edition (US 920803)",
	"Street Fighter II' - Champion Edition (Japan 920513)",
	"Street Fighter II' - Champion Edition (Rainbow set 1)",
	"Street Fighter II' - Champion Edition (Rainbow set 2)",
	"Street Fighter II' - Champion Edition (Red Wave)",
	"Street Fighter II! - Champion Edition (V004)",
	"Street Fighter II' - Champion Edition (Accelerator Pt.II)",
	"Varth - Operation Thunderstorm (World 920612)",
	"Varth - Operation Thunderstorm (US 920612)",
	"Varth - Operation Thunderstorm (Japan 920714)",
	"Capcom World 2 (Japan 920611)",
	"Warriors of Fate (World 921002)",
	"Sangokushi II (Asia 921005)",
	"Warriors of Fate (US 921031)",
	"Tenchi wo Kurau II - Sekiheki no Tatakai (Japan 921031)",
	"Street Fighter II' - Hyper Fighting (US 921209)",
	"Street Fighter II' Turbo - Hyper Fighting (Japan 921209)",
	"Cadillacs and Dinosaurs (World 930201)",
	"Cadillacs and Dinosaurs (US 930201)",
	"Cadillacs Kyouryuu-Shinseiki (Japan 930201)",
	"The Punisher (World 930422)",
	"The Punisher (US 930422)",
	"The Punisher (Japan 930422)",
	"Saturday Night Slam Masters (World 930713)",
	"Saturday Night Slam Masters (US 930713)",
	"Muscle Bomber - The Body Explosion (Japan 930713)",
	"Muscle Bomber Duo - Ultimate Team Battle (World 931206)",
	"Muscle Bomber Duo - Heat Up Warriors (Japan 931206)",
	"Pnickies (Japan 940608)",
	"Quiz &amp; Dragons (US 920701)",
	"Quiz &amp; Dragons (Japan 940921)",
	"Quiz Tonosama no Yabou 2 Zenkoku-ban (Japan 950123)",
	"Pang! 3 (Euro 950511)",
	"Pang! 3 (Japan 950511)",
	"Mega Man - The Power Battle (CPS1 Asia 951006)",
	"Rockman - The Power Battle (CPS1 Japan 950922)",
	},
	{ --DECO
	"Act-Fancer Cybernetick Hyper Weapon (Japan revision 1)",
	"Act-Fancer Cybernetick Hyper Weapon (World revision 1)",
	"Act-Fancer Cybernetick Hyper Weapon (World revision 2)",
	"Alpha Fighter / Head On",
	"Astro Fantasia (Cassette)",
	"Astro Fighter (set 1)",
	"Astro Fighter (set 2)",
	"Astro Fighter (set 3)",
	"Avengers In Galactic Storm (Japan)",
	"Backfire!",
	"Bad Dudes vs. Dragonninja (US)",
	"Battle Rangers (World)",
	"Battle Wings",
	"Battle Wings (alt)",
	"Birdie Try (Japan)",
	"Bloody Wolf (US)",
	"Boogie Wings (Asia v1.5, 92.12.07)",
	"Boogie Wings (Euro v1.5, 92.12.07)",
	"Boomer Rang'r / Genesis",
	"Boulder Dash (Cassette)",
	"Boulder Dash / Boulder Dash Part 2 (Japan)",
	"Boulder Dash / Boulder Dash Part 2 (World)",
	"Break Thru (US)",
	"Breywood (Japan revision 2)",
	"Bump 'n' Jump",
	"Bump N Jump (Cassette)",
	"Burger Time (Cassette)",
	"Burger Time (Data East set 1)",
	"Burger Time (Data East set 2)",
	"Burger Time (Midway)",
	"Burnin' Rubber",
	"Burnin' Rubber (Cassette, set 1)",
	"Burnin' Rubber (Cassette, set 2)",
	"B-Wings (Japan)",
	"Captain America and The Avengers (Asia Rev 1.0)",
	"Captain America and The Avengers (Asia Rev 1.9)",
	"Captain America and The Avengers (Japan Rev 0.2)",
	"Captain America and The Avengers (UK Rev 1.4)",
	"Captain America and The Avengers (US Rev 1.6)",
	"Captain America and The Avengers (US Rev 1.9)",
	"Captain Silver (Japan)",
	"Caveman Ninja (US)",
	"Caveman Ninja (World revision 0)",
	"Caveman Ninja (World revision 3)",
	"Chain Reaction",
	"Chelnov - Atomic Runner (Japan)",
	"Chelnov - Atomic Runner (US)",
	"Chelnov - Atomic Runner (World)",
	"China Town (Japan)",
	"Cobra-Command (Japan)",
	"Cobra-Command (World revision 5)",
	"Competition Golf Final Round (old version)",
	"Competition Golf Final Round (revision 3)",
	"Counter Steer",
	"Crude Buster (Japan)",
	"Crude Buster (World FU version)",
	"Crude Buster (World FX version)",
	"Dark Seal (Japan)",
	"Dark Seal (World revision 1)",
	"Dark Seal (World revision 3)",
	"Dark Seal 2 (Japan v2.1)",
	"Darwin 4078 (Japan)",
	"Death Brade (Japan Rev 2, JM-3)",
	"Desert Assault (US 4 Players)",
	"Desert Assault (US)",
	"Diet Go Go (Euro v1.1 1992.08.04)",
	"Diet Go Go (Euro v1.1 1992.09.26)",
	"Diet Go Go (Japan v1.1 1992.09.26)",
	"Diet Go Go (USA v1.1 1992.09.26)",
	"Disco No.1",
	"Disco No.1 (Cassette)",
	"Disco No.1 (Rev.F)",
	"Dragon Gun (US)",
	"Dragonninja (Japan)",
	"Dual Assault",
	"Dunk Dream '95",
	"Explorer (Cassette)",
	"Express Raider (US set 2)",
	"Express Raider (US)",
	"Fighter's History (US Alternate Hardware)",
	"Fighter's History (US)",
	"Fighter's History (World)",
	"Fighting Fantasy (Japan revision 2)",
	"Fighting Fantasy (Japan)",
	"Fighting Ice Hockey (Cassette)",
	"Fire Trap (US)",
	"Flying Ball? (Cassette)",
	"Funky Jet",
	"Garyo Retsuden (Japan)",
	"Gate of Doom (US revision 1)",
	"Gate of Doom (US revision 4)",
	"Gekitsui Oh (Japan)",
	"Gondomania (US)",
	"Graplop (aka Cluster Buster) (Cassette, set 1)",
	"Graplop (aka Cluster Buster) (Cassette, set 2)",
	"Gun Ball (Japan)",
	"Heavy Barrel (US)",
	"Heavy Barrel (World)",
	"Heavy Smash",
	"Highway Chase? (Cassette)",
	"Hippodrome (US)",
	"Hoops '96",
	"Joe &amp; Mac Returns",
	"Joe &amp; Mac Returns (set 2)",
	"Kamikaze Cabbie",
	"Karate Champ (US VS version)",
	"Karate Champ (US)",
	"Karate Dou (Japan)",
	"Karnov (Japan)",
	"Karnov (US)",
	"Kuhga - Operation Code 'Vapor Trail' (Japan revision 3)",
	"Kyohkoh-Toppa (Japan)",
	"Last Mission (Japan)",
	"Last Mission (US revision 5)",
	"Last Mission (US revision 6)",
	"Lemmings (US Prototype)",
	"Liberation",
	"Locked 'n Loaded (US)",
	"Lock'n'Chase",
	"Lock'n'Chase (Cassette)",
	"Lucky Poker (Cassette)",
	"Mad Alien",
	"Magical Drop",
	"Magical Drop Plus",
	"Makyou Senshi (Japan)",
	"Mausuke no Ojama the World (J 960314 V1.000)",
	"Meikyuu Hunter G (Japan)",
	"Metal Clash (Japan)",
	"Midnight Resistance (Japan)",
	"Midnight Resistance (US)",
	"Midnight Resistance (World)",
	"Mission-X (Cassette)",
	"Mutant Fighter (World Rev 3, EM-4)",
	"Mutant Fighter (World Rev 4, EM-5)",
	"Night Slashers",
	"Night Star (Cassette, set 1)",
	"Night Star (Cassette, set 2)",
	"Nitro Ball (US)",
	"Peter Pepper's Ice Cream Factory (Cassette, set 1)",
	"Peter Pepper's Ice Cream Factory (Cassette, set 2)",
	"Pocket Gal (Japan)",
	"Pocket Gal 2 (World?)",
	"Pocket Gal Deluxe (Euro v3.00)",
	"Pro Baseball Skill Tryout (Japan)",
	"Pro Bowling (Cassette)",
	"Pro Golf (Cassette)",
	"Pro Soccer",
	"Pro Soccer (Cassette)",
	"Pro Tennis (Cassette)",
	"Prosport",
	"Psycho-Nics Oscar (Japan revision 0)",
	"Psycho-Nics Oscar (Japan revision 1)",
	"Psycho-Nics Oscar (Japan revision 2)",
	"Psycho-Nics Oscar (US)",
	"Ring King (US set 1)",
	"Ring King (US set 2)",
	"Ring King (US set 3)",
	"Robocop (Japan)",
	"Robocop (US revision 0)",
	"Robocop (US revision 1)",
	"Robocop (World revision 3)",
	"Robocop (World revision 4)",
	"Robocop 2 (Japan)",
	"Robocop 2 (US)",
	"Robocop 2 (World)",
	"Rohga Armour Force (Asia/Europe v3.0)",
	"Rohga Armour Force (Hong Kong v3.0)",
	"Rohga Armour Force (US v1.0)",
	"Rootin' Tootin' (aka La.Pa.Pa) (Cassette)",
	"Rootin' Tootin' (Cassette)",
	"Scrum Try (Cassette, set 1)",
	"Scrum Try (Cassette, set 2)",
	"Secret Agent (World)",
	"Shackled (US)",
	"Shoot Out (Japan)",
	"Shoot Out (US)",
	"Side Pocket (Japan)",
	"Side Pocket (World)",
	"Skull Fang (Japan)",
	"Sly Spy (US revision 2)",
	"Sly Spy (US revision 3)",
	"Stadium Hero (Japan)",
	"Stadium Hero 96 (Version EAD)",
	"Stadium Hero 96 (Version EAJ)",
	"Suikoenbu (J 950314 V2.001)",
	"Super Astro Fighter (Cassette)",
	"Super Burger Time (Japan)",
	"Super Burger Time (World)",
	"Super Doubles Tennis",
	"Super Pool III (I-Vics)",
	"Super Pool III (World?)",
	"Super Real Darwin (Japan)",
	"Super Real Darwin (World)",
	"Sweet Heart (Cassette)",
	"Taisen Karate Dou (Japan VS version)",
	"Tatakae Genshizin Joe &amp; Mac (Japan)",
	"Tattoo Assassins (Asia Prototype)",
	"Tattoo Assassins (US Prototype)",
	"Terranean (Cassette)",
	"Test Tape (Cassette)",
	"The Cliffhanger - Edward Randy (Japan)",
	"The Cliffhanger - Edward Randy (World revision 1)",
	"The Cliffhanger - Edward Randy (World revision 2)",
	"The Real Ghostbusters (US 2 Players)",
	"The Real Ghostbusters (US 3 Players)",
	"Thunder Zone (World)",
	"Tomahawk 777 (Revision 1)",
	"Tomahawk 777 (Revision 5)",
	"Tornado (Cassette)",
	"Treasure Island (Cassette, set 1)",
	"Treasure Island (Cassette, set 2)",
	"Treasure Island (Cassette, set 3)",
	"Trio The Punch - Never Forget Me... (Japan)",
	"Trio The Punch - Never Forget Me... (World)",
	"Tumble Pop (Japan)",
	"Tumble Pop (World)",
	"Two Crude (US)",
	"Vapor Trail - Hyper Offence Formation (US)",
	"Vapor Trail - Hyper Offence Formation (World revision 1)",
	"Western Express (World?)",
	"Wizard Fire (US v1.1)",
	"Wonder Planet (Japan)",
	"World Cup Volley '95",
	"Zaviga",
	"Zaviga (Japan)",
	"Zero Target (World)",
	"Zeroize? (Cassette)",
	"Zoar",
	},
	{ --DYNAX
	"7jigen no Youseitachi - Mahjong 7 Dimensions (Japan)",
	"Asylum (prototype)",
	"Ataxx (Japan)",
	"Ataxx (set 1)",
	"Ataxx (set 2)",
	"Brute Force",
	"Danny Sullivan's Indy Heat",
	"Don Den Lover Vol. 1 (Hong Kong)",
	"Dragon Punch (Japan)",
	"Golden Fire II",
	"Hana Fubuki [BET] (Japan)",
	"Hana Kochou [BET] (Japan)",
	"Hana no Mai (Japan)",
	"Hana Oriduru (Japan)",
	"Hanakanzashi (Japan)",
	"Jong Tou Ki (Japan)",
	"Kyuukyoku no Othello",
	"Mahjong Angels - Comic Theater Vol.2 (Japan)",
	"Mahjong Campus Hunting (Japan)",
	"Mahjong Derringer (Japan)",
	"Mahjong Dial Q2 (Japan)",
	"Mahjong Diplomat [BET] (Japan)",
	"Mahjong Electron Base (parts 2 &amp; 3, alt., Japan)",
	"Mahjong Electron Base (parts 2 &amp; 3, Japan)",
	"Mahjong Electron Base (parts 2 &amp; 4, Japan)",
	"Mahjong Friday (Japan)",
	"Mahjong If [BET] (Japan)",
	"Mahjong Neruton Haikujirada (Japan)",
	"Mahjong Studio 101 [BET] (Japan)",
	"Mahjong Yarunara (Japan)",
	"Monkey Mole Panic (USA)",
	"Mosaic",
	"Mosaic (Fuuki)",
	"Nettoh Quiz Champion (Japan)",
	"Othello Derby (Japan)",
	"Pachinko Gindama Shoubu (Japan)",
	"Pachinko Gindama Shoubu DX (Japan)",
	"Quiz 365 (Hong Kong &amp; Taiwan)",
	"Quiz 365 (Japan)",
	"Quiz Channel Question (Ver 1.00) (Japan)",
	"Quiz Channel Question (Ver 1.23) (Taiwan?)",
	"Quiz TV Gassyuukoku Q&amp;Q (Japan)",
	"Rong Rong (Europe)",
	"Rong Rong (Germany)",
	"Shanghai (Japan)",
	"Shanghai II (Japan)",
	"Sports Match",
	"Tonton [BET] (Japan)",
	"Untouchable (Japan)",
	"World Soccer Finals",
	},
	{ --IREM
	"10-Yard Fight (Japan)",
	"Air Duel (Japan)",
	"Andromeda (Japan?)",
	"Atomic Boy",
	"Atomic Punk (US)",
	"Battle Chopper",
	"Blade Master (World)",
	"Bomber Man (Japan)",
	"Bomber Man World (Japan)",
	"Bomber Man World / New Dyna Blaster - Global Quest",
	"Cosmic Cop (World)",
	"Daiku no Gensan (Japan)",
	"Daiku no Gensan (Japan, M72)",
	"Demoneye-X",
	"Dragon Breed",
	"Dream Soccer '94",
	"Dream Soccer '94 (Japan)",
	"Dynablaster / Bomber Man",
	"Fire Barrel (Japan)",
	"Gallop - Armed police Unit (Japan)",
	"Geostorm (Japan)",
	"Gingateikoku No Gyakushu",
	"Green Beret (Irem)",
	"Gun Hohki (Japan)",
	"Gunforce - Battle Fire Engulfed Terror Island (Japan)",
	"Gunforce - Battle Fire Engulfed Terror Island (US)",
	"Gunforce - Battle Fire Engulfed Terror Island (World)",
	"Gunforce 2 (US)",
	"Gussun Oyoyo (Japan)",
	"Hammerin' Harry (US)",
	"Hammerin' Harry (World)",
	"Hasamu (Japan)",
	"Head On (Irem, M-15 Hardware)",
	"Hook (Japan)",
	"Hook (US)",
	"Hook (World)",
	"Horizon",
	"Image Fight (Japan)",
	"In The Hunt (US)",
	"In The Hunt (World)",
	"IPM Invader",
	"Kaiketsu Yanchamaru (Japan)",
	"Kaitei Daisensou (Japan)",
	"Ken-Go",
	"Kid Niki - Radical Ninja (US)",
	"Kung Fu (PlayChoice-10)",
	"Kung-Fu Master",
	"Kung-Fu Master (Data East)",
	"Legend of Hero Tonma",
	"Lethal Thunder (World)",
	"Lode Runner (set 1)",
	"Lode Runner (set 2)",
	"Lode Runner II - The Bungeling Strikes Back",
	"Lode Runner III - Majin No Fukkatsu",
	"Lode Runner III - The Golden Labyrinth",
	"Lode Runner IV - Teikoku Karano Dasshutsu",
	"Lot Lot",
	"Major Title (Japan)",
	"Major Title 2 (World)",
	"Meikyu Jima (Japan)",
	"Moon Patrol",
	"Moon Patrol (Williams)",
	"MotoRace USA",
	"Mr. HELI no Dai-Bouken",
	"Mystic Riders (World)",
	"New Atomic Punk - Global Quest (US)",
	"Ninja Baseball Batman (US)",
	"Ninja Spirit",
	"Oli-Boo-Chu",
	"Perfect Soldiers (Japan)",
	"Pound for Pound (US)",
	"Pound for Pound (World)",
	"Quiz F-1 1,2finish",
	"Red Alert",
	"Risky Challenge",
	"R-Type (Japan prototype)",
	"R-Type (Japan)",
	"R-Type (US)",
	"R-Type II",
	"R-Type II (Japan)",
	"R-Type Leo (Japan rev. D)",
	"R-Type Leo (World rev. C)",
	"Saigo no Nindou (Japan)",
	"Skins Game (Nintendo Super System)",
	"Sky Chuter",
	"Space Beam",
	"Spartan X (Japan)",
	"Spelunker",
	"Spelunker (Japan)",
	"Spelunker II",
	"Superior Soldiers (US)",
	"The Battle-Road",
	"The Irem Skins Game (US set 1)",
	"The Irem Skins Game (US set 2)",
	"Thunder Blaster (Japan)",
	"Traverse USA / Zippy Race",
	"Tropical Angel",
	"Undercover Cops (Japan)",
	"Undercover Cops (World)",
	"UniWar S",
	"Vigilante (Japan)",
	"Vigilante (US)",
	"Vigilante (World)",
	"Vs 10-Yard Fight (Japan)",
	"Vs 10-Yard Fight (World, 11/05/84)",
	"Wily Tower",
	"X Multiply (Japan)",
	"Yakyuu Kakutou League-Man (Japan)",
	"Youjyuden (Japan)",
	},
	{ --JALECO
	"Idol Janshi Su-Chi-Pie 2 (v1.1)",
	"Idol Janshi Su-Chi-Pie 2 (v1.0)",
	"64th. Street - A Detective Story (Japan)",
	"64th. Street - A Detective Story (World)",
	"Aeroboto",
	"Mahjong Angel Kiss",
	"Argus",
	"The Astyanax",
	"Avenging Spirit",
	"Best Bout Boxing",
	"Best League",
	"Big Run (11th Rallye version)",
	"Big Striker",
	"Big Striker (bootleg)",
	"Butasan (Japan)",
	"Chimera Beast (prototype)",
	"Cisco Heat",
	"City Connection (set 1)",
	"City Connection (set 2)",
	"Cruisin",
	"Cybattler",
	"D-Day (Jaleco)",
	"Desert War / Wangan Sensou",
	"E.D.F. : Earth Defense Force",
	"Exerion",
	"Exerion (bootleg)",
	"Exerion (Taito)",
	"Exerizer (Japan) (bootleg)",
	"Grand Prix Star",
	"F-1 Grand Prix Star II",
	"F1 Super Battle",
	"Field Combat",
	"Formation Z",
	"The Game Paradise - Master of Shooting! / Game Tengoku - The Game Paradise",
	"Ginga NinkyouDen (set 2)",
	"Ginga NinkyouDen (set 1)",
	"Gratia - Second Earth (92047-01 version)",
	"Gratia - Second Earth (91022-10 version)",
	"Hachoo!",
	"Hayaoshi Quiz Ouza Ketteisen",
	"Moero Pro Yakyuu Homerun",
	"Iga Ninjyutsuden (Japan)",
	"Jitsuryoku!! Pro Yakyuu (Japan)",
	"Kick Off (Japan)",
	"Ryuusei Janshi Kirara Star",
	"Legend of Makai (World)",
	"The Lord of King (Japan)",
	"Makai Densetsu (Japan)",
	"Momoko 120%",
	"P-47 - The Phantom Fighter (World)",
	"P-47 Aces",
	"P-47 - The Freedom Fighter (Japan)",
	"Peek-a-Boo!",
	"Phantasm (Japan)",
	"Plus Alpha",
	"Psychic 5",
	"Parallel Turn",
	"Rock'n Tread (Japan)",
	"Rod-Land (World)",
	"Rod-Land (Japan)",
	"Rod-Land (Japan bootleg)",
	"Scud Hammer",
	"Sky Fox",
	"Soldam (Japan)",
	"Saint Dragon",
	"Tetris Plus 2 (Japan)",
	"Tetris Plus",
	"Tetris Plus 2 (World?)",
	"Tetris Plus 2 (MegaSystem 32 Version)",
	"Takeda Shingen (Japan, Japanese)",
	"Shingen Samurai-Fighter (Japan, English)",
	"Valtric",
	"Wild Pilot",
	},
	{ --KANEKO
	"Air Buster: Trouble Specialty Raid Unit (Japan)",
	"Air Buster: Trouble Specialty Raid Unit (World)",
	"Bakuretsu Breaker",
	"The Berlin Wall (set 1)",
	"The Berlin Wall (set 2)",
	"Blaze On (Japan)",
	"Blood Warrior",
	"B.C. Kid / Bonk's Adventure / Kyukyoku!! PC Genjin",
	"B.Rap Boys",
	"Cyvern (Japan)",
	"DJ Boy",
	"Explosive Breaker",
	"Fujiyama Buster (Japan)",
	"Gals Panic II (Japan?)",
	"Gals Panic 3",
	"Gals Panic 4 (Japan)",
	"Gals Panic (set 3)",
	"Gals Panic (set 2)",
	"Gals Panic (set 1)",
	"Gals Panic S - Extra Edition (Japan)",
	"Gals Panic S2 (Japan)",
	"Gals Panic II - Quiz Version (Japan)",
	"Great 1000 Miles Rally",
	"Mille Miglia 2: Great 1000 Miles Rally (95/05/24)",
	"Mille Miglia 2: Great 1000 Miles Rally (95/04/04)",
	"Great 1000 Miles Rally 2 USA (95/05/18)",
	"Great 1000 Miles Rally (Evolution Model)",
	"Great 1000 Miles Rally (USA)",
	"Guts'n (Japan)",
	"Jackie Chan - The Kung-Fu Master",
	"Jackie Chan in Fists of Fire",
	"Jan Jan Paradise 2",
	"Jan Jan Paradise",
	"Magical Crystals (Japan)",
	"Magical Crystals (World)",
	"Panic Street (Japan)",
	"Puzz Loop (Japan)",
	"Puzz Loop (USA)",
	"Puzz Loop (Europe)",
	"VS Mahjong Otome Ryouran",
	"Sand Scorpion",
	"Saru-Kani-Hamu-Zou (Japan)",
	"Sengeki Striker (Japan)",
	"Sengeki Striker (Asia)",
	"Sen-Know (Japan)",
	"Shogun Warriors",
	"Tel Jan",
	"VS Block Breaker (Asia)",
	},
	{ --KONAMI
	"600",
	"Amidar",
	"Amidar (Olympia)",
	"Amidar (Scramble hardware)",
	"Amidar (Stern)",
	"Battlantis",
	"Battlantis (Japan)",
	"Blades of Steel (version E)",
	"Blades of Steel (version T)",
	"Boot Camp",
	"Bottom of the Ninth (version N)",
	"Bottom of the Ninth (version T)",
	"Castlevania (PlayChoice-10)",
	"Circus Charlie",
	"Circus Charlie (Centuri)",
	"Circus Charlie (Centuri, earlier)",
	"Circus Charlie (no level select)",
	"Combat School (Japan trackball)",
	"Combat School (joystick)",
	"Combat School (trackball)",
	"Contra (Japan)",
	"Contra (PlayChoice-10)",
	"Contra (US)",
	"Contra 3: The Alien Wars (Nintendo Super System)",
	"Dai Ressya Goutou (Japan)",
	"Devastators (ver. V)",
	"Devastators (ver. X)",
	"Devastators (ver. Z)",
	"Double Dribble",
	"Double Dribble (PlayChoice-10)",
	"Fast Lane",
	"Finalizer - Super Transformation",
	"Flak Attack (Japan)",
	"Frogger",
	"Frogger (Sega set 1)",
	"Frogger (Sega set 2)",
	"Garuka (Japan ver. W)",
	"Gradius (PlayChoice-10)",
	"Gradius (PlayChoice-10, older)",
	"Green Beret",
	"Gryzor",
	"Guttang Gottong",
	"Gyruss (Centuri)",
	"Gyruss (Konami)",
	"Hexion (Japan)",
	"Hyper Olympic",
	"Hyper Olympic '84",
	"Hyper Sports",
	"Iron Horse",
	"Jackal (World)",
	"Jail Break",
	"Jungler",
	"Jungler (Stern)",
	"Juno First",
	"Juno First (Gottlieb)",
	"Kicker",
	"Koi no Hotrock (Japan)",
	"Labyrinth Runner (Japan)",
	"Labyrinth Runner (World Ver. K)",
	"Lethal Enforcers (Japan ver JAD)",
	"Lethal Enforcers (US ver UAE)",
	"Loco-Motion",
	"Main Stadium (Japan)",
	"Manhattan 24 Bunsyo (Japan)",
	"Mega Zone (Interlogic + Kosuka)",
	"Mega Zone (Konami set 1)",
	"Mega Zone (Konami set 2)",
	"Mega Zone (Kosuka set 1)",
	"Mega Zone (Kosuka set 2)",
	"Mikie",
	"Mikie (High School Graffiti)",
	"Mogura Desse",
	"Mr. Goemon (Japan)",
	"MX5000",
	"Pandora's Palace",
	"Ping Pong",
	"Pooyan",
	"Pooyan (Stern)",
	"Rack 'em Up",
	"Ring no Ohja (Japan 2 Players ver. N)",
	"Road Fighter (set 1)",
	"Road Fighter (set 2)",
	"Rock 'n Rage (Prototype?)",
	"Rock 'n Rage (World?)",
	"Roc'n Rope",
	"Roc'n Rope (Kosuka)",
	"Rush'n Attack (PlayChoice-10)",
	"Rush'n Attack (US)",
	"S.P.Y. - Special Project Y (US ver. M)",
	"S.P.Y. - Special Project Y (World ver. N)",
	"Scooter Shooter",
	"Scramble",
	"Scramble (Stern)",
	"Shao-Lin's Road",
	"Shinnyuushain Tooru-kun",
	"Space King 2",
	"Strategy X",
	"Strategy X (Stern)",
	"Super Basketball (not encrypted)",
	"Super Basketball (version E)",
	"Super Basketball (version G)",
	"Super C (PlayChoice-10)",
	"Super Cobra",
	"Super Cobra (Sega)",
	"Super Cobra (Stern)",
	"Tactician (set 1)",
	"Tactician (set 2)",
	"Teenage Mutant Ninja Turtles (PlayChoice-10)",
	"Teenage Mutant Ninja Turtles II: The Arcade Game (PlayChoice-10)",
	"The End",
	"The End (Stern)",
	"The Goonies (PlayChoice-10)",
	"The Hustler (Japan version J)",
	"The Hustler (Japan version M)",
	"The Main Event (2 Players ver. X)",
	"The Main Event (4 Players ver. F)",
	"The Main Event (4 Players ver. Y)",
	"Time Pilot",
	"Time Pilot (Atari)",
	"Time Pilot (Centuri)",
	"Time Pilot '84 (set 1)",
	"Time Pilot '84 (set 2)",
	"Tokushu Butai Jackal (Japan)",
	"Top Gunner (US)",
	"Track &amp; Field",
	"Track &amp; Field (Centuri)",
	"Track &amp; Field (PlayChoice-10)",
	"Trick Trap (World?)",
	"Turpin",
	"Turtles",
	"Tutankham",
	"Tutankham (Stern)",
	"Video Hustler",
	"Vs. Castlevania",
	"Vs. Gradius",
	"Vs. The Goonies",
	"Vs. Top Gun",
	"Wizz Quiz (version ?)",
	"Yie Ar Kung-Fu (set 1)",
	"Yie Ar Kung-Fu (set 2)",
	},
	{ --KONAMI2
	"'88 Games",
	"Ajax",
	"Ajax (Japan)",
	"Akuma-Jou Dracula (Japan version N)",
	"Akuma-Jou Dracula (Japan version P)",
	"Aliens (Japan set 1)",
	"Aliens (Japan set 2)",
	"Aliens (US)",
	"Aliens (World set 1)",
	"Aliens (World set 2)",
	"Aliens (World set 3)",
	"Asterix (World ver. EAA)",
	"Asterix (World ver. EAC)",
	"Asterix (World ver. EAD)",
	"beatmania (ver JA-B)",
	"beatmania 2nd MIX (ver JA-A)",
	"beatmania 2nd MIX (ver JA-B)",
	"beatmania 4th MIX (ver JA-A)",
	"beatmania 5th MIX (ver JA-A)",
	"beatmania 6th MIX (ver JA-A)",
	"beatmania complete MIX (ver JA-B)",
	"beatmania complete MIX 2 (ver JA-A)",
	"beatmania CORE REMIX (ver JA-A)",
	"beatmania f. Dreams Come True (ver JA-A)",
	"Bells &amp; Whistles (Version L)",
	"Bishi Bashi Championship Mini Game Senshuken (Japan JAA)",
	"Black Panther",
	"Block Hole",
	"Bucky O'Hare (US version UA)",
	"Bucky O'Hare (World version EA)",
	"Chequered Flag",
	"Chequered Flag (Japan)",
	"City Bomber (Japan)",
	"City Bomber (World)",
	"Crazy Cop (Japan)",
	"Crime Fighters (Japan 2 Players)",
	"Crime Fighters (US 4 players)",
	"Crime Fighters (World 2 Players)",
	"Crime Fighters 2 (Japan 2 Players ver. P)",
	"Cue Brick (Japan)",
	"Cue Brick (World version D)",
	"Daisu-Kiss (ver JAA)",
	"Dark Adventure",
	"Detana!! Twin Bee (Japan ver. J)",
	"Devil World",
	"Dragoon Might (ver AAB)",
	"Dragoon Might (ver JAA)",
	"Escape Kids (Japan 2 Players)",
	"Fantastic Journey",
	"Gaiapolis (Japan ver JAF)",
	"Gaiapolis (US ver UAF)",
	"Galactic Warriors",
	"Gang Busters",
	"GI Joe (Japan)",
	"GI Joe (US)",
	"GI Joe (World)",
	"Gokujyou Parodius (ver JAD)",
	"Golfing Greats",
	"Golfing Greats (Japan)",
	"Golfing Greats 2 (ver JAC)",
	"Gradius",
	"Gradius II - GOFER no Yabou (Japan New Ver.)",
	"Gradius II - GOFER no Yabou (Japan Old Ver.)",
	"Gradius II - GOFER no Yabou (Japan Older Ver.)",
	"Gradius III (Asia)",
	"Gradius III (Japan)",
	"Gradius III (World ?)",
	"Hard Puncher (Japan)",
	"Haunted Castle (version K)",
	"Haunted Castle (version M)",
	"hiphopmania complete MIX (ver UA-B)",
	"hiphopmania complete MIX 2 (ver UA-A)",
	"Hot Chase",
	"Hyper Crash (version C)",
	"Hyper Crash (version D)",
	"Hyper Sports Special (Japan)",
	"Kitten Kaboodle",
	"Konami '88",
	"Konami GT",
	"Konami RF2 - Red Fighter",
	"Konami's Open Golf Championship (ver EAD)",
	"Konami's Open Golf Championship (ver EAE)",
	"Kyukyoku Sentai Dadandarn (Japan ver JAA)",
	"Lethal Enforcers II: Gun Fighters (ver EAA)",
	"Lethal Enforcers II: Gun Fighters (ver JAA)",
	"Lethal Enforcers II: Gun Fighters (ver UAA)",
	"Lifeforce (Japan)",
	"Lifeforce (US)",
	"Lightning Fighters (US)",
	"Lightning Fighters (World)",
	"M.I.A. - Missing in Action (Japan)",
	"M.I.A. - Missing in Action (version S)",
	"M.I.A. - Missing in Action (version T)",
	"Majuu no Ohkoku",
	"Martial Champion (Asia ver AAA)",
	"Martial Champion (Europe ver EAA)",
	"Martial Champion (Japan ver JAA)",
	"Martial Champion (US ver UAD)",
	"Metamorphic Force (Japan ver JAA)",
	"Metamorphic Force (US ver UAA)",
	"Monster Maulers (Europe ver EAA)",
	"Mystic Warriors (Europe ver EAA)",
	"Mystic Warriors (US ver UAA)",
	"Nemesis",
	"Nemesis (World?)",
	"Nyan Nyan Panic (Japan)",
	"Over Drive",
	"Parodius DA! (Japan)",
	"Parodius DA! (World)",
	"Polygonet Commanders (ver UAA)",
	"Premier Soccer (Europe ver. EAB)",
	"Premier Soccer (Japan ver. JAB)",
	"Punk Shot (Japan 2 Players)",
	"Punk Shot (US 2 Players)",
	"Punk Shot (US 4 Players)",
	"Quarth (Japan)",
	"Quiz Do Re Mi Fa Grand Prix (Japan)",
	"Quiz Do Re Mi Fa Grand Prix2 - Shin-Kyoku Nyuukadayo (Japan)",
	"Quiz Gakumon no Susume (Japan ver. JA2 Type L)",
	"Racin' Force (ver UAB)",
	"Rollergames (Japan)",
	"Rollergames (US)",
	"Run and Gun (US ver. UAB 1993 10.12)",
	"Run and Gun (US ver. UBA 1993 10.8)",
	"Run and Gun (World ver. EAA 1993 10.4)",
	"Run and Gun (World ver. EAA 1993 10.8)",
	"Run and Gun 2 (ver UAA)",
	"Rushing Heroes (ver UAB)",
	"Salamander (version D)",
	"Salamander (version J)",
	"Salamander 2 (ver JAA)",
	"Sexy Parodius (ver JAA)",
	"Slam Dunk (Japan ver. JAA 1993 10.8)",
	"Slam Dunk 2 (ver JAA)",
	"Soccer Superstars (ver AAA)",
	"Soccer Superstars (ver JAA)",
	"Sunset Riders (Asia 2 Players ver. ABD)",
	"Sunset Riders (Asia 4 Players ver. ADD)",
	"Sunset Riders (bootleg 4 Players ver. ADD)",
	"Sunset Riders (Japan 2 Players ver. JBD)",
	"Sunset Riders (US 2 Players ver. UBC)",
	"Sunset Riders (US 4 Players ver. UAC)",
	"Sunset Riders (US 4 Players ver. UDA)",
	"Sunset Riders (World 2 Players ver. EBC)",
	"Sunset Riders (World 2 Players ver. EBD)",
	"Sunset Riders (World 4 Players ver. EAC)",
	"Super Bishi Bashi Championship (Japan JAA)",
	"Super Contra",
	"Super Contra (Japan)",
	"Surprise Attack (Asia ver. L)",
	"Surprise Attack (Japan ver. M)",
	"Taisen Puzzle-dama (ver JAA)",
	"Taisen Tokkae-dama (ver JAA)",
	"Teenage Mutant Hero Turtles (UK 2 Players)",
	"Teenage Mutant Hero Turtles (UK 4 Players)",
	"Teenage Mutant Ninja Turtles - Turtles in Time (Asia 4 Players ver. ADA)",
	"Teenage Mutant Ninja Turtles - Turtles in Time (US 2 Players ver. UDA)",
	"Teenage Mutant Ninja Turtles - Turtles in Time (US 4 Players ver. UAA)",
	"Teenage Mutant Ninja Turtles (Japan 2 Players)",
	"Teenage Mutant Ninja Turtles (Japan 4 Players)",
	"Teenage Mutant Ninja Turtles (Oceania 2 Players)",
	"Teenage Mutant Ninja Turtles (US 4 Players, set 1)",
	"Teenage Mutant Ninja Turtles (US 4 Players, set 2)",
	"Teenage Mutant Ninja Turtles (World 4 Players)",
	"The Final Round (version L)",
	"The Final Round (version M)",
	"The Simpsons (2 Players alt)",
	"The Simpsons (2 Players Japan)",
	"The Simpsons (2 Players)",
	"The Simpsons (4 Players alt)",
	"The Simpsons (4 Players)",
	"Thunder Cross",
	"Thunder Cross (Japan)",
	"Thunder Cross (Set 2)",
	"Thunder Cross II (Asia)",
	"Thunder Cross II (Japan)",
	"Tokimeki Memorial Taisen Puzzle-dama (ver JAB)",
	"Trigon (Japan)",
	"Twin Bee Yahhoo! (ver JAA)",
	"TwinBee",
	"Typhoon",
	"Vendetta (Asia 2 Players ver. D)",
	"Vendetta (Asia 2 Players ver. U)",
	"Vendetta (World 2 Players ver. W)",
	"Vendetta (World 4 Players ver. R)",
	"Vendetta (World 4 Players ver. T)",
	"Versus Net Soccer (ver JAB)",
	"Versus Net Soccer (ver UAB)",
	"Violent Storm (Asia ver AAC)",
	"Violent Storm (Europe ver EAB)",
	"Violent Storm (Japan ver JAC)",
	"Violent Storm (US ver UAB)",
	"Vulcan Venture",
	"WEC Le Mans 24",
	"Wild West C.O.W.-Boys of Moo Mesa (US version UA)",
	"Wild West C.O.W.-Boys of Moo Mesa (World version EA)",
	"Winning Spike (ver EAA)",
	"Winning Spike (ver JAA)",
	"Xexex (Japan)",
	"Xexex (World)",
	"X-Men (Japan 2 Players)",
	"X-Men (US 4 Players)",
	"X-Men (US 6 Players)",
	"X-Men (World 2 Players)",
	},
	{ --NAMCO
	"Baraduke (set 1)",
	"Baraduke (set 2)",
	"Bomb Bee",
	"Bosconian (Midway, new version)",
	"Bosconian (Midway, old version)",
	"Bosconian (new version)",
	"Bosconian (old version)",
	"Bosconian (older version)",
	"Cutie Q",
	"Dig Dug (Atari, rev 1)",
	"Dig Dug (Atari, rev 2)",
	"Dig Dug (rev 1)",
	"Dig Dug (rev 2)",
	"Dig Dug II (New Ver.)",
	"Dig Dug II (Old Ver.)",
	"Dragon Buster",
	"Galaga (Midway set 1)",
	"Galaga (Midway set 2)",
	"Galaga (Namco rev. B)",
	"Galaga (Namco)",
	"Galaga 3 (rev. C)",
	"Galaga 3 (set 2)",
	"Galaga 3 (set 3)",
	"Galaxian (Midway)",
	"Galaxian (Midway, old rev)",
	"Galaxian (Namco set 1)",
	"Galaxian (Namco set 2)",
	"Gaplus (alternate hardware)",
	"Gaplus (rev. B)",
	"Gaplus (rev. D)",
	"Gee Bee",
	"Gee Bee (Gremlin)",
	"Genpei ToumaDen",
	"Grobda (New Ver.)",
	"Grobda (Old Ver. set 1)",
	"Grobda (Old Ver. set 2)",
	"Hopping Mappy",
	"Kaitei Takara Sagashi",
	"King &amp; Balloon (Japan)",
	"King &amp; Balloon (US)",
	"Mappy (Japan)",
	"Mappy (US)",
	"Metro-Cross (set 1)",
	"Metro-Cross (set 2)",
	"Motos",
	"Navarone",
	"New Rally X",
	"Pac &amp; Pal",
	"Pac &amp; Pal (older)",
	"Pac-Land (Midway)",
	"Pac-Land (set 1)",
	"Pac-Land (set 2)",
	"Pac-Land (set 3)",
	"Pac-Man &amp; Chomp Chomp",
	"Pac-Man (Midway)",
	"Pac-Man (Midway, harder)",
	"Pac-Man (Midway, with speedup hack)",
	"Pac-Man Plus",
	"Phozon (Japan)",
	"Pole Position",
	"Pole Position (Atari version 1)",
	"Pole Position (Atari version 2)",
	"Pole Position II",
	"Pole Position II (Atari)",
	"PuckMan (Japan set 1 with speedup hack)",
	"PuckMan (Japan set 1, Probably Bootleg)",
	"PuckMan (Japan set 2)",
	"PuckMan (Japan set 3)",
	"Rally X",
	"Rally X (Midway)",
	"Rolling Thunder (new version)",
	"Rolling Thunder (old version)",
	"Sky Kid (60A1 Ver.)",
	"Sky Kid (New Ver.)",
	"Sky Kid (Old Ver.)",
	"Sky Kid Deluxe (set 1)",
	"Sky Kid Deluxe (set 2)",
	"SOS",
	"Super Pac-Man",
	"Super Pac-Man (Midway)",
	"Super Xevious",
	"Tank Battalion",
	"The Return of Ishtar",
	"Tower of Druaga (New Ver.)",
	"Tower of Druaga (Old Ver.)",
	"Vs. Battle City",
	"Vs. Star Luster",
	"Vs. Super SkyKid",
	"Vs. Super Xevious",
	"Vs. TKO Boxing",
	"Warp &amp; Warp",
	"Warp Warp (Rock-ola set 1)",
	"Warp Warp (Rock-ola set 2)",
	"Wonder Momo",
	"Xevious (Atari set 1)",
	"Xevious (Atari set 2)",
	"Xevious (Atari set 3)",
	"Xevious (Namco)",
	},
	{ --NAMCO 2
	"Bakuretsu Quiz Ma-Q Dai Bouken (Japan)",
	"Cosmo Gang the Puzzle (Japan)",
	"Cosmo Gang the Puzzle (US)",
	"Emeraldia (Japan Version B)",
	"Emeraldia (Japan)",
	"Exvania (Japan)",
	"F/A (Japan)",
	"Fighter &amp; Attacker (US)",
	"Final Lap R",
	"Great Sluggers (Japan)",
	"Great Sluggers '94",
	"Gun Bullet (Japan)",
	"J-League Soccer V-Shoot",
	"Knuckle Heads (Japan)",
	"Knuckle Heads (World)",
	"Kosodate Quiz My Angel (Japan)",
	"Kosodate Quiz My Angel 2 (Japan)",
	"Libble Rabble",
	"Mach Breakers (Japan)",
	"Namco Classics Collection Vol.1",
	"Namco Classics Collection Vol.1 (Japan set 1)",
	"Namco Classics Collection Vol.1 (Japan set 2)",
	"Namco Classics Collection Vol.2",
	"Namco Classics Collection Vol.2 (Japan)",
	"Nebulas Ray (Japan)",
	"Nebulas Ray (World)",
	"Nettou! Gekitou! Quiztou!! (Japan)",
	"Numan Athletics (Japan)",
	"Numan Athletics (World)",
	"Outfoxies",
	"Outfoxies (Japan)",
	"Point Blank",
	"Speed Racer",
	"Super World Court (Japan)",
	"Super World Stadium '95 (Japan)",
	"Super World Stadium '96 (Japan)",
	"Super World Stadium '97 (Japan)",
	"Thunder Ceptor",
	"Thunder Ceptor II",
	"Tinkle Pit (Japan)",
	"Toypop",
	"X-Day 2 (Japan)",
	},
	{ --NICHIBUTSU
	"Armed Formation",
	"Bijokko Gakuen (Japan 880116)",
	"Bijokko Yume Monogatari (Japan 870925)",
	"City Love (Japan 860908)",
	"City Love [BET] (Japan 860904)",
	"Cop 01 (set 1)",
	"Cop 01 (set 2)",
	"Crazy Climber (Japan)",
	"Crazy Climber (US)",
	"Crazy Climber 2 (Japan Harder)",
	"Crazy Climber 2 (Japan)",
	"Crystal Gal (Japan 860512)",
	"Crystal Gal 2 (Japan 860620)",
	"Dacholer",
	"Dangar - Ufo Robo (12/1/1986)",
	"Dangar - Ufo Robo (9/26/1986)",
	"Frisky Tom (set 1)",
	"Frisky Tom (set 2)",
	"Galivan - Cosmo Police (12/11/1985)",
	"Galivan - Cosmo Police (12/16/1985)",
	"Gionbana (Japan 890120)",
	"Gionbana [BET] (Japan 890207)",
	"Gomoku Narabe Renju",
	"Hana to Ojisan [BET] (Japan 911209)",
	"House Mannequin (Japan 870217)",
	"House Mannequin Roppongi Live hen (Japan 870418)",
	"Iemoto (Japan 871020)",
	"Iemoto [BET] (Japan 871118)",
	"Kick Boy",
	"Kid no Hore Hore Daisakusen",
	"Kodure Ookami (Japan)",
	"Legion (ver 1.05)",
	"Legion (ver 2.03)",
	"Mag Max",
	"Mahjong Bakuhatsu Junjouden (Japan)",
	"Mahjong Chinmoku no Hentai (Japan 900511)",
	"Mahjong Circuit no Mehyou (Japan)",
	"Mahjong CLUB 90's (set 1) (Japan 900919)",
	"Mahjong CLUB 90's (set 2) (Japan 900919)",
	"Mahjong Final Bunny [BET] (Japan)",
	"Mahjong Focus (Japan 890313)",
	"Mahjong Focus [BET] (Japan 890510)",
	"Mahjong Gal no Kaika (Japan)",
	"Mahjong Gal no Kokuhaku (Japan)",
	"Mahjong G-MEN'89 (Japan 890425)",
	"Mahjong Gottsu ee-kanji (Japan)",
	"Mahjong Hana no Momoko gumi (Japan 881201)",
	"Mahjong Housoukyoku Honbanchuu (Japan)",
	"Mahjong Hyouban Musume [BET] (Japan)",
	"Mahjong Janjan Baribari (Japan)",
	"Mahjong Jikken Love Story (Japan)",
	"Mahjong Keibaou (Japan)",
	"Mahjong Koi no Magic Potion (Japan)",
	"Mahjong Koi Uranai (Japan)",
	"Mahjong Koi Uranai (set 2) (Japan)",
	"Mahjong La Man (Japan)",
	"Mahjong Love House [BET] (Japan 901024)",
	"Mahjong Nerae! Top Star (Japan)",
	"Mahjong Pachinko Monogatari (Japan)",
	"Mahjong Panic Stadium (Japan)",
	"Mahjong Sailor Wars (Japan)",
	"Mahjong Sailor Wars (Japan) (set 2)",
	"Mahjong Sailor Wars-R [BET] (Japan)",
	"Mahjong Satsujin Jiken (Japan 881017)",
	"Mahjong Shikaku (Japan 880722)",
	"Mahjong Shikaku (Japan 880802)",
	"Mahjong Shikaku (Japan 880806)",
	"Mahjong Shikaku (Japan 880908)",
	"Mahjong Shikaku [BET] (Japan 880929)",
	"Mahjong THE LADY HUNTER (Japan 900509)",
	"Mahjong Triple Wars (Japan)",
	"Mahjong Triple Wars 2 (Japan)",
	"Mahjong Uchuu yori Ai wo komete (Japan)",
	"Mahjong Uranai Densetsu (Japan)",
	"Mahjong Vanilla Syndrome (Japan)",
	"Mahjong Wakuwaku Catcher (Japan)",
	"Mahjong Yoshimoto Gekijou (Japan)",
	"Mahjong-zukino Korinai Menmen (Japan 880425)",
	"Mahjong-zukino Korinai Menmen [BET] (Japan 880920)",
	"Maikobana (Japan 900802)",
	"Maikobana [BET] (Japan 900911)",
	"Medal Mahjong Circuit no Mehyou [BET] (Japan)",
	"Medal Mahjong Gottsu ee-kanji [BET] (Japan)",
	"Medal Mahjong Janjan Baribari [BET] (Japan)",
	"Medal Mahjong Pachi-Slot Tengoku [BET] (Japan)",
	"Mighty Guy",
	"Miss Mahjong Contest (Japan)",
	"Moon Alien",
	"Moon Alien Part 2",
	"Moon Alien Part 2 (older version)",
	"Moon Base",
	"Moon Cresta (bootleg set 2)",
	"Moon Cresta (Nichibutsu)",
	"Moon Cresta (Nichibutsu, old rev)",
	"Moon Cresta (Nichibutsu, unencrypted)",
	"Moon Quasar",
	"Moon Shuttle (Japan set 2)",
	"Moon Shuttle (Japan)",
	"Moon Shuttle (US?)",
	"Musoubana (Japan)",
	"Nekketsu Grand-Prix Gal (Japan)",
	"Ninja Emaki (US)",
	"Niyanpai (Japan)",
	"Ojousan (Japan 871204)",
	"Ojousan [BET] (Japan 870108)",
	"Pairs (Nichibutsu) (Japan 890822)",
	"Pastel Gal (Japan 851224)",
	"Quiz-Mahjong Hayaku Yatteyo! (Japan)",
	"Radical Radial",
	"Roller Jammer",
	"Rolling Crash / Moon Base",
	"Rug Rats",
	"Scandal Mahjong (Japan 890213)",
	"Scandal Mahjong [BET] (Japan 890217)",
	"Second Love (Japan 861201)",
	"Sector Zone",
	"Sei Senshi Amatelass",
	"Seicross",
	"Seiha (Japan 870725)",
	"Seiha [BET] (Japan 870723)",
	"SF-X",
	"Skelagon",
	"Soldier Girl Amazon",
	"Super GX",
	"Taisen Quiz HYHOO (Japan)",
	"Taisen Quiz HYHOO 2 (Japan)",
	"Tatakae! Big Fighter",
	"Telephone Mahjong (Japan 890111)",
	"Terra Cresta (YM2203)",
	"Terra Cresta (YM3526 set 1)",
	"Terra Cresta (YM3526 set 2)",
	"Terra Force",
	"Terra Force (US)",
	"Tokimeki Bishoujo [BET] (Japan)",
	"Tokyo Gal Zukan (Japan)",
	"Tube Panic",
	"Wiping",
	"Youma Ninpou Chou (Japan)",
	},
	{ --NINTENDO
	"Arm Wrestling",
	"Balloon Fight (PlayChoice-10)",
	"Baseball (PlayChoice-10)",
	"Donkey Kong (Japan set 1)",
	"Donkey Kong (Japan set 2)",
	"Donkey Kong (Japan set 3) (bad dump?)",
	"Donkey Kong (US set 1)",
	"Donkey Kong (US set 2)",
	"Donkey Kong 3 (Japan)",
	"Donkey Kong 3 (US)",
	"Donkey Kong Jr. (Japan)",
	"Donkey Kong Junior (bootleg?)",
	"Donkey Kong Junior (Japan?)",
	"Donkey Kong Junior (US)",
	"Dr. Mario (PlayChoice-10)",
	"Duck Hunt (PlayChoice-10)",
	"Excite Bike (PlayChoice-10)",
	"F-Zero (Nintendo Super System)",
	"Golf (PlayChoice-10)",
	"HeliFire (set 1)",
	"HeliFire (set 2)",
	"Hogan's Alley (PlayChoice-10)",
	"Mario Bros. (Japan)",
	"Mario Bros. (PlayChoice-10)",
	"Mario Bros. (US)",
	"Mario's Open Golf (PlayChoice-10)",
	"Metroid (PlayChoice-10)",
	"Mike Tyson's Punch-Out!! (PlayChoice-10)",
	"Popeye (revision D not protected)",
	"Popeye (revision D)",
	"Popeye (revision F)",
	"Pro Wrestling (PlayChoice-10)",
	"Punch-Out!!",
	"Radar Scope",
	"Sheriff",
	"Sky Skipper",
	"Space Demon",
	"Space Fever (set 1)",
	"Space Fever (set 2)",
	"Space Fever High Splitter (set 1)",
	"Space Fever High Splitter (set 2)",
	"Space Firebird (Nintendo)",
	"Space Launcher",
	"Super Mario Bros. (PlayChoice-10)",
	"Super Mario Bros. 2 (PlayChoice-10)",
	"Super Mario Bros. 3 (PlayChoice-10)",
	"Super Mario World (Nintendo Super System)",
	"Super Punch-Out!!",
	"Super Punch-Out!! (Japan)",
	"Super Tennis (Nintendo Super System)",
	"Tennis (PlayChoice-10)",
	"Volley Ball (PlayChoice-10)",
	"Vs. Balloon Fight",
	"Vs. BaseBall",
	"Vs. BaseBall (Japan set 1)",
	"Vs. BaseBall (Japan set 2)",
	"Vs. BaseBall (Japan set 3)",
	"Vs. Clu Clu Land",
	"Vs. Dr. Mario",
	"Vs. Duck Hunt",
	"Vs. Excitebike",
	"Vs. Excitebike (Japan)",
	"Vs. Gumshoe",
	"Vs. Hogan's Alley",
	"Vs. Ice Climber",
	"Vs. Ice Climber (Japan)",
	"Vs. Ice Climber Dual (Japan)",
	"Vs. Mach Rider (Endurance Course Version)",
	"Vs. Mach Rider (Japan, Fighting Course Version)",
	"Vs. Mahjang (Japan)",
	"Vs. Pinball",
	"Vs. Pinball (Japan)",
	"Vs. Raid on Bungeling Bay (Japan)",
	"Vs. Soccer",
	"Vs. Stroke &amp; Match Golf (Ladies Version)",
	"Vs. Stroke &amp; Match Golf (Men set 2)",
	"Vs. Stroke &amp; Match Golf (Men Version)",
	"Vs. Stroke &amp; Match Golf (Men Version) (Japan)",
	"Vs. Super Mario Bros.",
	"Vs. Tennis",
	"Vs. Tennis (Japan)",
	"Vs. Wrecking Crew",
	"Wild Gunman (PlayChoice-10)",
	},
	{ --SEGA
	"005",
	"Ali Baba and 40 Thieves",
	"Angel Kids (Japan)",
	"Astro Blaster (version 1)",
	"Astro Blaster (version 2)",
	"Astro Blaster (version 2a)",
	"Astro Blaster (version 3)",
	"Astro Flash (Japan)",
	"Block Gal",
	"Borderline",
	"Buck Rogers: Planet of Zoom",
	"Buck Rogers: Planet of Zoom (not encrypted)",
	"Calorie Kun vs Moguranian",
	"Carnival (cocktail)",
	"Carnival (upright)",
	"Champion Baseball",
	"Champion Baseball II (set 1)",
	"Champion Boxing",
	"Champion Pro Wrestling",
	"Choplifter",
	"Choplifter (alternate)",
	"Commando (Sega)",
	"Congo Bongo",
	"DakkoChan Jansoh",
	"Digger",
	"Dottori Kun (new version)",
	"Dottori Kun (old version)",
	"Fantasy Zone 2",
	"Flashgal (set 1)",
	"Flashgal (set 2)",
	"Flicky (128k Ver.)",
	"Flicky (64k Ver.)",
	"Future Spy",
	"Gardia",
	"Hang-On Jr.",
	"Head On 2",
	"Heavy Metal",
	"Hopper Robo",
	"Invinco",
	"Invinco / Deep Scan",
	"Invinco / Head On 2",
	"Ixion (prototype)",
	"KO Punch",
	"Legend",
	"Mister Viking",
	"Mister Viking (Japan)",
	"Monster Bash",
	"Monster Bash (2 board version)",
	"My Hero (US)",
	"Ninja",
	"Ninja Princess (128k Ver.)",
	"Ninja Princess (64k Ver. not encrypted)",
	"N-Sub",
	"Opa Opa",
	"Pengo (set 1 rev c)",
	"Pengo (set 2 not encrypted)",
	"Pengo (set 2)",
	"Pengo (set 3 not encrypted)",
	"Pengo (set 4)",
	"Pig Newton (version A)",
	"Pig Newton (version C)",
	"Pitfall II",
	"Pitfall II (not encrypted)",
	"Pulsar",
	"Razzmatazz",
	"Regulus (New Ver.)",
	"Regulus (not encrypted)",
	"Regulus (Old Ver.)",
	"Repulse",
	"Riddle of Pythagoras (Japan)",
	"Robo Wres 2001",
	"Samurai",
	"Sanrin San Chan (Japan)",
	"Sega Ninja",
	"Sega Ninja (not encrypted)",
	"Shooting Master",
	"Sindbad Mystery",
	"Space Attack (cocktail)",
	"Space Attack (upright set 1)",
	"Space Attack (upright set 2)",
	"Space Attack (upright set 3)",
	"Space Attack / Head On",
	"Space Fury (revision A)",
	"Space Fury (revision C)",
	"Space Odyssey",
	"Space Position (Japan)",
	"Space Tactics",
	"Space Trek (cocktail)",
	"Space Trek (upright)",
	"Spatter",
	"Star Jacker (Sega)",
	"Star Trek",
	"Subroc-3D",
	"Super Locomotive",
	"Super Zaxxon",
	"Tac/Scan",
	"TeddyBoy Blues (New Ver.)",
	"TeddyBoy Blues (Old Ver.)",
	"Tip Top",
	"Toki no Senshi - Chrono Soldier",
	"Tranquilizer Gun",
	"Transformer",
	"Turbo",
	"Turbo (encrypted set 1)",
	"Turbo (encrypted set 2)",
	"Ufo Senshi Yohko Chan",
	"Up'n Down",
	"Up'n Down (not encrypted)",
	"Water Match",
	"Wonder Boy (not encrypted)",
	"Wonder Boy (set 1, new encryption)",
	"Wonder Boy (set 1, old encryption)",
	"Wonder Boy (set 2 not encrypted)",
	"Wonder Boy (set 2)",
	"Wonder Boy (set 3)",
	"Wonder Boy Deluxe",
	"Wonder Boy in Monster Land (Japan New Ver.)",
	"Wonder Boy in Monster Land (Japan Old Ver.)",
	"Yamato (US)",
	"Yamato (World?)",
	"Zaxxon (set 1)",
	"Zaxxon (set 2)",
	"Zektor (revision B)",
	},
	{ --SEGA2
	"A.B. Cop (FD1094 317-0169b)",
	"Ace Attacker (FD1094 317-unknown)",
	"Action Fighter, FD1089A 317-0018",
	"After Burner (Japan)",
	"After Burner (Mega-Tech)",
	"After Burner II",
	"Alex Kidd: The Lost Stars (set 1, FD1089A 317-unknown)",
	"Alex Kidd: The Lost Stars (set 2, unprotected)",
	"Alien Storm (Mega-Tech",
	"Alien Storm (set 1, Japan, 2 Players, FD1094 317-0146)",
	"Alien Storm (set 2, US, 3 Players, FD1094 317-0147)",
	"Alien Storm (set 3, World, 3 Players, FD1094 317-0148)",
	"Alien Storm (set 4, 2 Players, FD1094 317-?)",
	"Alien Syndrome (Mega-Tech)",
	"Alien Syndrome (set 1, System 16A, FD1089A 317-0033)",
	"Alien Syndrome (set 2, System 16A, FD1089A 317-0033)",
	"Alien Syndrome (set 3, System 16B, FD1089A 317-0033)",
	"Alien Syndrome (set 4, System 16B, unprotected)",
	"Altered Beast (Mega-Tech)",
	"Altered Beast (set 2, MC-8123B 317-0066)",
	"Altered Beast (set 4, MC-8123B 317-0066)",
	"Altered Beast (set 5, 8751 317-0076)",
	"Altered Beast (set 7, 8751 317-0078)",
	"Arnold Palmer Tournament Golf (Mega-Tech)",
	"Arrow Flash (Mega-Tech)",
	"Astro Warrior (Mega-Tech)",
	"Aurail (set 1, Japan, FD1089A 317-0167)",
	"Aurail (set 2, World, FD1089B 317-0168)",
	"Aurail (set 3, US, unprotected)",
	"Bio-hazard Battle (Mega Play)",
	"Bloxeed (C System)",
	"Bloxeed (Japan, FD1094 317-0139)",
	"Bloxeed (US, C System)",
	"Body Slam (8751 317-unknown)",
	"Bonanza Bros",
	"Bonanza Bros. (Mega-Tech)",
	"Borench",
	"Bullet (FD1094 317-0041)",
	"Clutch Hitter (set 1, Japan, FD1094 317-0175)",
	"Clutch Hitter (set 2, US, FD1094 317-0176)",
	"Columns (Japan)",
	"Columns (Mega-Tech)",
	"Columns (US)",
	"Columns II: The Voyage Through Time",
	"Columns II: The Voyage Through Time (Japan)",
	"Cotton (set 1, Japan, FD1094 317-0179a)",
	"Cotton (set 2, US, FD1094 317-0180)",
	"Cotton (set 3, World, FD1094 317-0181a)",
	"Crack Down (Mega-Tech)",
	"Crack Down (US, FD1094 317-0058-04d)",
	"Cyber Police ESWAT: Enhanced Special Weapons and Tactics (Mega-Tech)",
	"D. D. Crew (set 1, World, 4 Player, FD1094 317-?)",
	"D. D. Crew (set 2, World, 2 Player, FD1094 317-0184)",
	"D. D. Crew (set 3, US, 4 Player, FD1094 317-0186)",
	"D. D. Crew (set 4, World, 3 Player, FD1094 317-0190)",
	"D. D. Crew (set 5, Japan, 2 Player, FD1094 317-0182)",
	"Defense (System 16B, FD1089A 317-0028)",
	"Desert Breaker (FD1094 317-0196)",
	"Dump Matsumoto (Japan, 8751 317-unknown))",
	"Dunk Shot (FD1089 317-0022)",
	"Dynamic Country Club",
	"Dynamic Country Club (Floppy DS3-5000-09d, FD1094 317-0058-09d)",
	"Dynamite Dux (FD1094 317-0096)",
	"Enduro Racer (FD1089B 317-unknown)",
	"E-Swat - Cyber Police (set 1, Japan, FD1094 317-0128)",
	"E-Swat - Cyber Police (set 2, US, FD1094 317-0129)",
	"E-Swat - Cyber Police (set 3, World, FD1094 317-0130)",
	"Excite League (FD1094 317-0079?)",
	"Fantasy Zone (set 1, unprotected)",
	"Fantasy Zone (set 2, unprotected)",
	"Flash Point (Japan, FD1094 317-0127A)",
	"Gain Ground (FD1094 317-0058-03?)",
	"Galaxy Force 2",
	"Galaxy Force 2 (Japan)",
	"G-LOC Air Battle (US)",
	"Golden Axe (Mega-Tech)",
	"Golden Axe (set 1, World, FD1094 317-0110)",
	"Golden Axe (set 2, US, 8751 317-0112)",
	"Golden Axe (set 3, World, FD1094 317-0120)",
	"Golden Axe (set 4, Japan, FD1094 317-0121)",
	"Golden Axe (set 5, US, FD1094 317-0122)",
	"Golden Axe (set 6, US, 8751 317-123A)",
	"Golden Axe II (Mega Play)",
	"Golden Axe II (Mega-Tech)",
	"GP Rider (set 1, US, FD1094 317-0162)",
	"GP Rider (set 2, FD1094 317-0163)",
	"Grand Slam (Mega Play)",
	"Great Golf (Mega-Tech)",
	"Great Soccer (Mega-Tech)",
	"Hang-On",
	"Heavyweight Champ",
	"Hot Rod (Japan, 4 Players)",
	"Hot Rod (World, 3 Players, Turbo set 1)",
	"Hot Rod (World, 3 Players, Turbo set 2)",
	"Ichidant-R (Puzzle &amp; Action 2) (English)",
	"Ichidant-R (Puzzle &amp; Action 2) (Japan)",
	"Joe Montana II: Sports Talk Football (Mega-Tech)",
	"Jumbo Ozaki Super Masters Golf (FD1094 317-0058-05c)",
	"Jyuohki (set 1, Japan, FD1094 317-0065)",
	"Jyuohki (set 3, Japan, FD1094 317-0068)",
	"Jyuohki (set 6, Japan, 8751 317-0077)",
	"Kid Chameleon (Mega-Tech)",
	"Laser Ghost (set 1, US, 317-0165)",
	"Laser Ghost (set 2, World, 317-0166)",
	"Last Battle (Mega-Tech)",
	"Limited Edition Hang-On",
	"Line of Fire / Bakudan Yarou (Japan, FD1094 317-0134)",
	"Line of Fire / Bakudan Yarou (World, FD1094 317-0136)",
	"Major League",
	"Mazin Wars (Mega Play)",
	"Michael Jackson's Moonwalker (set 1, Japan, FD1094/8751 317-0157)",
	"Michael Jackson's Moonwalker (set 2, US, FD1094/8751 317-0158)",
	"Michael Jackson's Moonwalker (set 3, World, FD1094/8751 317-0159)",
	"Moonwalker (Mega-Tech)",
	"MVP (set 1, Japan, FD1094 317-0142)",
	"MVP (set 2, US, FD1094 317-0143)",
	"Mystic Defender (Mega-Tech)",
	"Out Run (set 1, Deluxe?)",
	"Out Run (set 2)",
	"Out Run (set 3)",
	"Parlour Games (Mega-Tech)",
	"Passing Shot (2 Players, FD1094 317-0080)",
	"Passing Shot (Japan, 4 Players, FD1094 317-0070)",
	"Pontoon",
	"Poto Poto (Japan)",
	"Power Drift",
	"Power Drift (Japan)",
	"Puyo Puyo (Japan)",
	"Puyo Puyo (Japan, Rev A)",
	"Puyo Puyo (World)",
	"Quartet (8751 317-unknown)",
	"Quartet (Japan, 8751 317-unknown))",
	"Quartet 2 (8751 317-unknown)",
	"Quartet 2 (Japan, 8751 317-unknown)",
	"Quiz Ghost Hunter",
	"Quiz Mekurumeku Story",
	"Quiz Rouka Ni Tattenasai",
	"Quiz Syukudai wo Wasuremashita",
	"Racing Hero (FD1094 317-0144)",
	"Rail Chase (Japan)",
	"Ribbit!",
	"Riot City (Japan)",
	"Rough Racer (FD1094 317-0058-06d)",
	"Scramble Spirits",
	"Scramble Spirits (FD1094 317-0058-02c)",
	"SDI - Strategic Defense Initiative (Europe, System 16A, FD1089B 317-0027)",
	"Shadow Dancer (set 1)",
	"Shadow Dancer (set 2, Japan)",
	"Shadow Dancer (set 3, US)",
	"Shinobi (Mega-Tech)",
	"Shinobi (set 1, System 16A, FD1094 317-0050)",
	"Shinobi (set 2, System 16B, FD1094 317-0049)",
	"Shinobi (set 3, System 16B, unprotected)",
	"Shinobi (set 4, System 16B, unprotected)",
	"Shinobi (set 5, System 16A, unprotected)",
	"Sonic Boom (FD1094 317-0053)",
	"Sonic The Hedgehog (Mega Play)",
	"Sonic The Hedgehog (Mega-Tech, set 1)",
	"Sonic The Hedgehog (Mega-Tech, set 2)",
	"Sonic The Hedgehog 2 (Mega Play)",
	"Sonic The Hedgehog 2 (Mega-Tech)",
	"Space Harrier",
	"Space Harrier II (Mega-Tech)",
	"Stack Columns (Japan)",
	"Streets of Rage II (Mega Play)",
	"Strike Fighter (Japan)",
	"Super Hang-On (Mega-Tech)",
	"Super Hang-On (set 1, FD1089B 317-0034)",
	"Super Hang-On (set 2, FD1089B 317-0034)",
	"Super Hang-On (set 3, FD1089B 317-0034)",
	"Super Hang-On (set 4, 68000)",
	"Super League (FD1094 317-0045?)",
	"Super Masters Golf (FD1094 317-0058-05d?)",
	"Super Monaco GP (Mega-Tech)",
	"Super Monaco GP (set 1, Japan, Rev B, FD1094 317-0124a)",
	"Super Monaco GP (set 2, US, Rev A, FD1094 317-0125a)",
	"Super Monaco GP (set 3, US, Rev B? FD1094 317-0125a)",
	"Super Monaco GP (set 4, US, Rev C, FD1094 317-0125a)",
	"Super Monaco GP (set 5, World, 'Air Drive Cabinet', FD1094 317-0126)",
	"Super Monaco GP (set 6, World, Rev A, FD1094 317-0126a)",
	"Super Monaco GP (set 7, World, Rev B, 'Twin', FD1094 317-0126a)",
	"Super Thunder Blade (Mega-Tech)",
	"Tant-R (Puzzle &amp; Action) (Japan)",
	"Tecmo World Cup (Mega Play)",
	"Tetris (Japan, B-System, YM2203)",
	"Tetris (Japan, B-System, YM2610)",
	"Tetris (Mega-Tech)",
	"Tetris (set 1, Japan, System 16B, FD1094 317-0091)",
	"Tetris (set 2, Japan, System 16B, FD1094 317-0092)",
	"Tetris (set 3, Japan, System 16A, FD1094 317-0093a)",
	"Tetris (set 4, Japan, System 16A, FD1094 317-0093)",
	"The Revenge of Shinobi (Mega-Tech)",
	"Thunder Blade (FD1094 317-0056)",
	"Thunder Blade (Japan)",
	"ThunderForce AC",
	"ThunderForce AC (Japan)",
	"Tokoro San no MahMahjan",
	"Tokoro San no MahMahjan 2",
	"Tommy Lasorda Baseball (Mega-Tech)",
	"Toryumon",
	"Tough Turf (set 1, US, 8751 317-0099)",
	"Tough Turf (set 2, Japan, 8751 317-0104)",
	"Turbo Out Run (set 1, FD1094 317-unknown)",
	"Turbo Out Run (set 2, upright, FD1094 317-unknown)",
	"Turbo Out Run (set 3, upgrade kit, FD1094 317-0118)",
	"Twin Squash",
	"Wally wo Sagase! (rev A, Japan, FD1094 317-0197A)",
	"Wally wo Sagase! (rev B, Japan, FD1094 317-0197B)",
	"Wonder Boy III - Monster Lair (set 1, System 16A, FD1094 317-0084)",
	"Wonder Boy III - Monster Lair (set 2, Japan, System 16B, FD1094 317-0085)",
	"Wonder Boy III - Monster Lair (set 3, World, System 16B, FD1094 317-0089)",
	"Wonder Boy III - Monster Lair (set 4, Japan, System 16B, FD1094 317-0087)",
	"Wonder Boy III - Monster Lair (set 5, World, System 16B, 8751 317-0098)",
	"World Championship Soccer (Mega-Tech)",
	"Wrestle War (set 1, Japan, FD1094 317-0090)",
	"Wrestle War (set 2, World, FD1094 317-0102)",
	"Wrestle War (set 3, World, 8751 317-0103)",
	"Zunzunkyou No Yabou (Japan)",
	},
	{ --SEGA3
	"Air Rescue",
	"Alien3: The Gun",
	"Arabian Fight (Japan)",
	"Arabian Fight (US)",
	"Baku Baku Animal (J 950407 V1.000)",
	"Behind Enemy Lines",
	"Burning Rival (Japan)",
	"Burning Rival (World)",
	"Columns '97 (JET 961209 V1.000)",
	"Cool Riders",
	"Dark Edge (Japan)",
	"Dark Edge (World)",
	"Daytona USA (Japan)",
	"Daytona USA (Japan, To The MAXX)",
	"Daytona USA (Japan, Turbo hack)",
	"Daytona USA 2",
	"Dead or Alive (Model 2A)",
	"Dead or Alive (Model 2B)",
	"Decathlete (JUET 960424 V1.000)",
	"Desert Tank",
	"Die Hard Arcade (UET 960515 V1.000)",
	"Dirt Devils",
	"Dragon Ball Z V.R.V.S.",
	"Dynamite Baseball '97",
	"Dynamite Cop (Model 2A)",
	"Dynamite Cop (Model 2B)",
	"Dynamite Deka (J 960515 V1.000)",
	"Dynamite Deka 2 (Japan, Model 2A)",
	"Ejihon Tantei Jimusyo (J 950613 V1.000)",
	"F1 Exhaust Note",
	"F1 Super Lap",
	"Fighting Vipers",
	"Final Arch (J 950714 V1.001)",
	"Funky Head Boxers (JUETBKAL 951218 V1.000)",
	"Golden Axe - The Duel (JUETL 950117 V1.000)",
	"Golden Axe: The Revenge of Death Adder (Japan)",
	"Golden Axe: The Revenge of Death Adder (US)",
	"Golden Axe: The Revenge of Death Adder (World)",
	"Gunblade NY",
	"Hanagumi Taisen Columns - Sakura Wars (J 971007 V1.010)",
	"Hard Dunk (Japan)",
	"Hard Dunk (World)",
	"Harley-Davidson and L.A. Riders",
	"Holosseum (US)",
	"House of the Dead",
	"Indianapolis 500",
	"Jurassic Park",
	"Last Bronx (Export, Rev A)",
	"Last Bronx (Japan, Rev A)",
	"Manx TT Superbike",
	"Maru-Chan de Goo! (J 971216 V1.000)",
	"OutRunners (US)",
	"Rad Mobile (US)",
	"Rad Mobile (World)",
	"Rad Rally (US)",
	"Rad Rally (World)",
	"Sando-R (J 951114 V1.000)",
	"Scud Race (Australia)",
	"Scud Race (Export)",
	"Sega Bass Fishing",
	"Sega Rally 2",
	"Sega Rally Championship",
	"Sega Touring Car Championship",
	"SegaSonic The Hedgehog (Japan, prototype)",
	"SegaSonic The Hedgehog (Japan, rev. C)",
	"Sky Target",
	"Sonic The Fighters",
	"Spider-Man: The Videogame (US)",
	"Spider-Man: The Videogame (World)",
	"Sport Fishing 2 (J 951201 V1.100)",
	"Sport Fishing 2 (UET 951106 V1.10e)",
	"Stadium Cross (World)",
	"Star Wars Arcade",
	"Star Wars Trilogy",
	"Super Major League (U 960108 V1.000)",
	"Super Visual Football: European Sega Cup",
	"Super Visual Soccer: Sega Cup (US)",
	"Taisen Tanto-R Sashissu!! (J 980216 V1.000)",
	"The J.League 1994 (Japan)",
	"The Lost World",
	"Title Fight (US)",
	"Title Fight (World)",
	"Top Skater",
	"Treasure Hunt (JUET 970901 V2.00E)",
	"Virtua Cop",
	"Virtua Cop 2",
	"Virtua Fighter",
	"Virtua Fighter 2 (original)",
	"Virtua Fighter 2 (ver 2.1)",
	"Virtua Fighter 2 (ver B)",
	"Virtua Fighter 3",
	"Virtua Fighter 3 Team Battle",
	"Virtua Fighter Kids (JUET 960319 V0.000)",
	"Virtua Fighter Remix (JUETBKAL 950428 V1.000)",
	"Virtua Formula",
	"Virtua Racing",
	"Virtua Striker",
	"Virtua Striker (Rev A)",
	"Virtua Striker 2 (Step 1.5)",
	"Virtua Striker 2 (Step 2.0)",
	"Virtua Striker 2 '98 (Step 1.5)",
	"Virtua Striker 2 '98 (Step 2.0)",
	"Virtua Striker 2 '99",
	"Virtua Striker 2 '99.1",
	"Virtual On 2: Oratorio Tangram",
	"Virtual On 2: Oratorio Tangram (ver 5.4g)",
	"Virtual On Cyber Troopers (Japan)",
	"Virtual On Cyber Troopers (US)",
	"Wing War",
	"Wing War (US)",
	"Winter Heat (JUET 971012 V1.000)",
	"Zen Nippon Pro-Wrestling Featuring Virtua (J 971123 V1.000)",
	},
	{ --SETA
	"Eleven Beat",
	"Arbalester",
	"Athena no Hatena ?",
	"Blandia",
	"Blandia (prototype)",
	"Block Carnival / Thunder &amp; Lightning 2",
	"Change Air Blade (Japan)",
	"Caliber 50",
	"Daioh",
	"DownTown",
	"DownTown (prototype)",
	"Dragon Unit / Castle of Dragon",
	"Drift Out '94 - The Hard Order (Japan)",
	"Dyna Gears",
	"Eagle Shot Golf",
	"Eagle Shot Golf (alt)",
	"Eight Forces",
	"Extreme Downhill (v1.5)",
	"Mobile Suit Gundam Final Shooting",
	"Guardians / Denjin Makai II",
	"Mobile Suit Gundam EX Revue",
	"Gundhara",
	"Hana Awase (Flower Matching)",
	"Mahjong Hyper Reaction 2 (Japan)",
	"Mahjong Hyper Reaction (Japan)",
	"Lovely Pop Mahjong Jan Jan Shimasyo (Japan)",
	"J. J. Squawkers",
	"Joryuu Syougi Kyoushitsu (Japan)",
	"Masked Riders Club Battle Race",
	"Dramatic Adventure Quiz Keith &amp; Lucy (Japan)",
	"Pro Mahjong Kiwame",
	"Koi Koi Shimasyo 2 - Super Real Hanafuda (Japan)",
	"Krazy Bowl",
	"Mad Shark",
	"Mayjinsen",
	"Mayjinsen 2",
	"Meosis Magic (Japan)",
	"Meta Fox",
	"Wakakusamonogatari Mahjong Yonshimai (Japan)",
	"Mahjong Yuugi (Japan set 1)",
	"Mahjong Yuugi (Japan set 2)",
	"Mobile Suit Gundam (Japan)",
	"Mobile Suit Gundam",
	"Monster Slider (Japan)",
	"Magical Tetris Challenge (981009 Japan)",
	"Kosodate Quiz My Angel (Japan)",
	"Kosodate Quiz My Angel 2 (Japan)",
	"SD Gundam Neo Battling (Japan)",
	"Neratte Chu",
	"Oishii Puzzle Ha Irimasenka",
	"Pairs Love",
	"Penguin Brothers (Japan)",
	"Mahjong Pon Chin Kan (Japan set 1)",
	"Mahjong Pon Chin Kan (Japan set 2)",
	"Puzzle De Bowling (Japan)",
	"Quiz Kokology 2",
	"Quiz Kokology",
	"Renju Kizoku",
	"Rezon",
	"Rezon (Taito)",
	"Gourmet Battle Quiz Ryohrioh CooKing (Japan)",
	"Sokonuke Taisen Game (Japan)",
	"Speed Attack!",
	"Super Eagle Shot (set 2)",
	"Super Eagle Shot (set 1)",
	"Super Real Mahjong Part 2 (Japan)",
	"Super Real Mahjong Part 3 (Japan)",
	"Super Real Mahjong PIV (Japan)",
	"Super Real Mahjong PIV (Japan, older set)",
	"Super Real Mahjong P5",
	"Super Real Mahjong P6 (Japan)",
	"Super Real Mahjong P7 (Japan)",
	"Strike Gunner S.T.G",
	"Storm Blade (US)",
	"Survival Arts",
	"Survival Arts (USA)",
	"Pachinko Sexy Reaction 2 (Japan)",
	"Pachinko Sexy Reaction (Japan)",
	"Thunder &amp; Lightning",
	"Thundercade / Twin Formation",
	"Tokusyu Butai U.A.G. (Japan)",
	"Triple Fun",
	"Twin Eagle II - The Rescue Mission",
	"Twin Eagle - Revenge Joe's Brother",
	"Ultra X Weapons / Ultra Keibitai",
	"Ultraman Club - Tatakae! Ultraman Kyoudai!!",
	"U.S. Classic",
	"Ultra Toukon Densetsu (Japan)",
	"Vasara",
	"Vasara 2 (set 1)",
	"Vasara 2 (set 2)",
	"Wiggie Waggie",
	"Wit's (Japan)",
	"War of Aero - Project MEIOU",
	"Zing Zing Zip",
	"Zombie Raid (US)",
	},
	{ --SNK
	"Alpha Mission",
	"ASO - Armored Scrum Object",
	"Athena",
	"Baseball Stars: Be a Champ! (PlayChoice-10)",
	"Beast Busters (World ?)",
	"Bermuda Triangle (Japan old version)",
	"Bermuda Triangle (Japan)",
	"Bermuda Triangle (US older version)",
	"Buriki One (rev.B)",
	"Chopper I (US set 1)",
	"Chopper I (US set 2)",
	"Chopper I (US set 3)",
	"Country Club",
	"Datsugoku - Prisoners of War (Japan)",
	"Dogou Souken",
	"Fantasy (Japan)",
	"Fantasy (US)",
	"Fantasy (World)",
	"Fatal Fury: Wild Ambition (rev.A)",
	"Fighting Golf (US)",
	"Fighting Golf (World?)",
	"Fighting Soccer",
	"Genshi-Tou 1930's",
	"Gladiator 1984",
	"Gold Medalist",
	"Gold Medalist (alt)",
	"Guerrilla War (US)",
	"Guerrilla War (Version 1)",
	"Guevara (Japan)",
	"HAL21",
	"HAL21 (Japan)",
	"Ikari (Japan)",
	"Ikari III - The Rescue",
	"Ikari Warriors (US)",
	"Joyful Road (Japan)",
	"Jumping Cross",
	"Koukuu Kihei Monogatari - The Legend of Air Cavalry (Japan)",
	"Lasso",
	"Mad Crasher",
	"Mahjong Block Jongbou (Japan)",
	"Main Event (1984)",
	"Marvin's Maze",
	"Mechanized Attack (World)",
	"Meijinsen",
	"Munch Mobile (US)",
	"Ozma Wars (set 1)",
	"Ozma Wars (set 2)",
	"P.O.W. - Prisoners of War (US)",
	"Paddle Mania",
	"Pioneer Balloon",
	"Prehistoric Isle in 1930 (US)",
	"Prehistoric Isle in 1930 (World)",
	"Psycho Soldier (Japan)",
	"Psycho Soldier (US)",
	"Roads Edge / Round Trip (rev.B)",
	"Safari Rally (Japan)",
	"Samurai Shodown: Warrior's Rage",
	"SAR - Search And Rescue (US)",
	"SAR - Search And Rescue (World)",
	"Sasuke vs. Commander",
	"Satan of Saturn",
	"Street Smart (Japan version 1)",
	"Street Smart (US version 1)",
	"Street Smart (US version 2)",
	"Street Smart (World version 1)",
	"T.A.N.K. (Japan)",
	"T.N.K. III (US)",
	"The Next Space",
	"TouchDown Fever",
	"TouchDown Fever (Japan)",
	"TouchDown Fever 2",
	"Vanguard (Centuri)",
	"Vanguard (Japan)",
	"Vanguard (SNK)",
	"Vanguard II",
	"Victory Road",
	"World Wars (World)",
	},
	{ --TAITO
	"Alpine Ski (set 1)",
	"Alpine Ski (set 2)",
	"American Horseshoes (US)",
	"Arkanoid - Revenge of DOH (Japan)",
	"Arkanoid - Revenge of DOH (US)",
	"Arkanoid - Revenge of DOH (World)",
	"Arkanoid (Japan)",
	"Arkanoid (US)",
	"Arkanoid (US, older)",
	"Arkanoid (World)",
	"Balloon Bomber",
	"Ben Bero Beh (Japan)",
	"Big Event Golf",
	"Bio Attack",
	"Birdie King",
	"Birdie King 2",
	"Birdie King 3",
	"Bubble Bobble",
	"Bubble Bobble (older)",
	"Bubble Bobble (US with mode select)",
	"Bubble Bobble (US)",
	"Buggy Challenge",
	"Buggy Challenge (Tecfri)",
	"Cachat (Japan)",
	"Chack'n Pop",
	"Champion Wrestler (Japan)",
	"Champion Wrestler (US)",
	"Champion Wrestler (World)",
	"Change Lanes",
	"Chuka Taisen (Japan)",
	"Chuka Taisen (US)",
	"Chuka Taisen (World)",
	"Colony 7 (set 1)",
	"Colony 7 (set 2)",
	"Complex X",
	"Crazy Balloon (set 1)",
	"Crazy Balloon (set 2)",
	"Cuby Bop (Location Test)",
	"Cycle Shooting",
	"Dock Man",
	"Dr. Toppel's Adventure (US)",
	"Dr. Toppel's Adventure (World)",
	"Dr. Toppel's Tankentai (Japan)",
	"Elevator Action",
	"Extermination (US)",
	"Exzisus (Japan)",
	"Field Day",
	"Fighting Hawk (Japan)",
	"Fighting Hawk (World)",
	"Fire Battle",
	"Fitter",
	"Forty-Love",
	"Front Line",
	"Galaxy Rescue",
	"Galaxy Wars (Taito?)",
	"Get Star (Japan)",
	"Gladiator (US)",
	"Go Go Mr. Yamaguchi / Yuke Yuke Yamaguchi-kun",
	"Grand Champion",
	"Great Gurianos (Japan?)",
	"Great Swordsman (Japan?)",
	"Great Swordsman (World?)",
	"Guardian",
	"Gyrodine",
	"Gyrodine (Crux)",
	"Halley's Comet (Japan set 1)",
	"Halley's Comet (Japan set 2)",
	"Halley's Comet (US)",
	"High Way Race",
	"Insector X (World)",
	"Joshi Volleyball",
	"Jump Coaster (Taito)",
	"Jungle Hunt (Brazil)",
	"Jungle Hunt (US)",
	"Jungle King (Japan)",
	"Jungle King (Japan, earlier)",
	"Kabuki-Z (Japan)",
	"Kabuki-Z (World)",
	"Kageki (Japan)",
	"Kageki (US)",
	"Kick and Run",
	"Kick Start Wheelie King",
	"KiKi KaiKai",
	"Kram (encrypted)",
	"Kram (set 1)",
	"Kram (set 2)",
	"Kuri Kinton (Japan)",
	"Kuri Kinton (US)",
	"Kuri Kinton (World)",
	"Kuri Kinton (World, prototype?)",
	"Kusayakyuu",
	"Land Sea Air Squad / Riku Kai Kuu Saizensen",
	"Lunar Rescue",
	"Lupin III",
	"Mahjong",
	"Marine Date",
	"Metal Soldier Isaac II",
	"Minivader",
	"N.Y. Captor",
	"Nunchackun",
	"Ohgon no Siro (Japan)",
	"Onna Sansirou - Typhoon Gal (set 1)",
	"Onna Sansirou - Typhoon Gal (set 2)",
	"Palamedes (Japan)",
	"Phoenix (Taito)",
	"Ping-Pong King",
	"Pirate Pete",
	"Pit &amp; Run (set 1)",
	"Pit &amp; Run (set 2)",
	"Plotting (World set 1)",
	"Plotting (World set 2)",
	"Plump Pop (Japan)",
	"Polaris (set 1)",
	"Polaris (set 2)",
	"Power Blade (PlayChoice-10)",
	"Prebillian",
	"Puzznic (Japan)",
	"Qix (set 1)",
	"Qix (set 2)",
	"Qix (set 3)",
	"Qix II (Tournament)",
	"Raimais (Japan)",
	"Return of the Invaders",
	"Ring Fighter (set 1)",
	"Ring Fighter (set 2)",
	"Rock Climber",
	"S.R.D. Mission",
	"Samurai Nihon-ichi (set 1)",
	"Samurai Nihon-ichi (set 2)",
	"Sea Fighter Poseidon",
	"Slap Fight",
	"Space Chaser",
	"Space Chaser (CV version)",
	"Space Cruiser",
	"Space Dungeon",
	"Space Invaders (CV Version)",
	"Space Invaders (SV Version 2)",
	"Space Invaders (SV Version)",
	"Space Invaders (TV Version)",
	"Space Invaders Part II (Taito)",
	"Space Seeker",
	"Storming Party / Riku Kai Kuu Saizensen",
	"Straight Flush",
	"Strike Bowling",
	"Sub Hunter",
	"Super Mouse",
	"Super Qix (set 1)",
	"Super Qix (set 2)",
	"Super Speed Race Junior (Japan)",
	"The Electric Yo-Yo (set 1)",
	"The Electric Yo-Yo (set 2)",
	"The FairyLand Story",
	"The FairyLand Story (Japan)",
	"The Legend of Kage",
	"The Lost Castle In Darkmist",
	"The NewZealand Story (Japan)",
	"The NewZealand Story (World, newer)",
	"The NewZealand Story (World, older)",
	"The Tin Star",
	"The Undoukai (Japan)",
	"Tiger Heli (Japan set 1)",
	"Tiger Heli (Japan set 2)",
	"Tiger Heli (US)",
	"Time Tunnel",
	"Tokio / Scramble Formation (US)",
	"Tournament Arkanoid (US)",
	"Tube-It",
	"Victorious Nine",
	"Vs. Hot Smash",
	"Water Ski",
	"Wild Western (set 1)",
	"Wild Western (set 2)",
	"Zoo Keeper (set 1)",
	"Zoo Keeper (set 2)",
	"Zoo Keeper (set 3)",
	},
	{ --TAITO2
	"Ah Eikou no Koshien (Japan)",
	"Air Inferno (US)",
	"Akkanvader (Japan)",
	"Aqua Jack (Japan)",
	"Aqua Jack (World)",
	"Arabian Magic (Japan)",
	"Arabian Magic (US)",
	"Arabian Magic (World)",
	"Arkanoid Returns (Japan)",
	"Ashura Blaster (Japan)",
	"Ashura Blaster (US)",
	"Asuka &amp; Asuka (Japan)",
	"Battle Shark (Japan)",
	"Battle Shark (US)",
	"Bonze Adventure (US)",
	"Bonze Adventure (World)",
	"Bubble Bobble 2 (World)",
	"Bubble Memories - The Story Of Bubble Bobble 3 (Japan)",
	"Bubble Memories - The Story Of Bubble Bobble 3 (World)",
	"Bubble Symphony (Europe)",
	"Bubble Symphony (Japan)",
	"Bubble Symphony (US)",
	"Bust-A-Move Again (US)",
	"Cadash (France)",
	"Cadash (Italy)",
	"Cadash (Japan)",
	"Cadash (US)",
	"Cadash (World)",
	"Cameltry (Japan)",
	"Cameltry (US)",
	"Cameltry (US, alt sound)",
	"Chase H.Q. (Japan)",
	"Chase H.Q. (World)",
	"Cleopatra Fortune (Japan)",
	"Command War - Super Special Battle &amp; War Game (Prototype)",
	"Continental Circus (US set 1)",
	"Continental Circus (US set 2)",
	"Continental Circus (World)",
	"Crayon Shinchan Orato Asobo (Japan)",
	"Crime City (Japan)",
	"Crime City (US)",
	"Crime City (World)",
	"Daisenpu (Japan)",
	"Dan-Ku-Ga (Prototype)",
	"Darius (Extra) (Japan)",
	"Darius (Japan old version)",
	"Darius (Japan)",
	"Darius (World)",
	"Darius Gaiden - Silver Hawk (Extra Version) [Official Hack]",
	"Darius Gaiden - Silver Hawk (Japan)",
	"Darius Gaiden - Silver Hawk (US)",
	"Darius Gaiden - Silver Hawk (World)",
	"Darius II (dual screen) (Japan old version)",
	"Darius II (dual screen) (Japan)",
	"Darius II (Japan)",
	"Dead Connection (Japan)",
	"Dead Connection (World)",
	"Densya De Go",
	"Densya De Go 2",
	"Densya De Go 2 Ex",
	"Densya De Go Ex",
	"Dino Rex (Japan)",
	"Dino Rex (US)",
	"Dino Rex (World)",
	"Don Doko Don (Japan)",
	"Don Doko Don (US)",
	"Don Doko Don (World)",
	"Double Axle (US)",
	"Dungeon Magic (US)",
	"Dungeon Magic (World)",
	"Dynamite League (Japan)",
	"Elevator Action 2 (US)",
	"Elevator Action Returns (Japan)",
	"Elevator Action Returns (World)",
	"Enforce (Japan)",
	"Euro Champ '92 (World)",
	"Field Goal",
	"Field Goal (different)",
	"Final Blow (Japan)",
	"Final Blow (US)",
	"Final Blow (World)",
	"Football Champ (World)",
	"Full Throttle (Japan)",
	"Gekirindan (Japan)",
	"Global Champion (US)",
	"Grid Seeker: Project Stormhammer (Japan)",
	"Grid Seeker: Project Stormhammer (US)",
	"Grid Seeker: Project Stormhammer (World)",
	"Ground Effects / Super Ground Effects (Japan)",
	"Growl (US)",
	"Growl (World)",
	"Gun &amp; Frontier (World)",
	"Gun Frontier (Japan)",
	"Gunbuster (Japan)",
	"Gunlock (World)",
	"Hat Trick Hero (Japan)",
	"Hat Trick Hero '93 (Japan)",
	"Hat Trick Hero '94 (US)",
	"Hat Trick Hero '95 (Japan)",
	"Hat Trick Hero '95 (US)",
	"International Cup '94 (World)",
	"Jigoku Meguri (Japan)",
	"Kaiser Knuckle (Japan)",
	"Kaiser Knuckle (World)",
	"Kirameki Star Road (Japan)",
	"Kyukyoku Tiger 2 (Japan)",
	"Land Maker (Japan)",
	"Land Maker (World Prototype)",
	"Landing Gear",
	"Light Bringer (Japan)",
	"Liquid Kids (US)",
	"Liquid Kids (World)",
	"Mahjong Quest (Japan)",
	"Mahjong Quest (No Nudity)",
	"Majestic Twelve - The Space Invaders Part IV (Japan)",
	"Master of Weapon (World)",
	"Maze of Flott (Japan)",
	"Mega Blast (Japan)",
	"Mega Blast (World)",
	"Metal Black (Japan)",
	"Metal Black (World)",
	"Mizubaku Daibouken (Japan)",
	"Moriguchi Hiroko no Quiz de Hyuu!Hyuu! (Japan)",
	"Nastar (World)",
	"Nastar Warrior (US)",
	"Night Striker (US)",
	"Operation Thunderbolt (Japan)",
	"Operation Thunderbolt (US)",
	"Operation Thunderbolt (US, older)",
	"Operation Thunderbolt (World)",
	"Operation Wolf (US)",
	"Operation Wolf (World)",
	"Operation Wolf 3 (US)",
	"Operation Wolf 3 (World)",
	"Pop 'N Pop (Japan)",
	"Pop 'N Pop (US)",
	"Pop 'N Pop (World)",
	"Power Wheels (Japan)",
	"Prime Time Fighter (US new version)",
	"Prime Time Fighter (US old version)",
	"Puchi Carat (Japan)",
	"Puchi Carat (World)",
	"PuLiRuLa (Japan)",
	"PuLiRuLa (World)",
	"Puzzle Bobble (Japan, B-System)",
	"Puzzle Bobble 2 (Japan)",
	"Puzzle Bobble 2 (World)",
	"Puzzle Bobble 2X (Japan)",
	"Puzzle Bobble 3 (Japan)",
	"Puzzle Bobble 3 (US)",
	"Puzzle Bobble 3 (World)",
	"Puzzle Bobble 4 (Japan)",
	"Puzzle Bobble 4 (US)",
	"Puzzle Bobble 4 (World)",
	"Quiz Chikyu Bouei Gun (Japan)",
	"Quiz Crayon Shinchan (Japan)",
	"Quiz H.Q. (Japan)",
	"Quiz Jinsei Gekijoh (Japan)",
	"Quiz Quest - Hime to Yuusha no Monogatari (Japan)",
	"Quiz Sekai wa SHOW by shobai (Japan)",
	"Quiz Theater - 3tsu no Monogatari (Japan)",
	"Quiz Torimonochou (Japan)",
	"Racing Beat (World)",
	"Rainbow Islands (Extra)",
	"Rainbow Islands (new version)",
	"Rainbow Islands (old version)",
	"Rambo III (Europe set 1)",
	"Rambo III (Europe set 2)",
	"Rambo III (US)",
	"Rastan (US set 1)",
	"Rastan (US set 2)",
	"Rastan (World)",
	"Rastan Saga (Japan)",
	"Rastan Saga 2 (Japan)",
	"Rayforce (Japan)",
	"Rayforce (US)",
	"Recalhorn (Prototype)",
	"Recordbreaker (World)",
	"Riding Fight (Japan)",
	"Riding Fight (US)",
	"Riding Fight (World)",
	"Ring Rage (Japan)",
	"Ring Rage (US)",
	"Ring Rage (World)",
	"Runark (Japan)",
	"Ryu Jin (Japan)",
	"Side By Side",
	"Side By Side 2",
	"Silent Dragon (Japan)",
	"Silent Dragon (World)",
	"Slap Shot (Japan)",
	"Solitary Fighter (World)",
	"Sonic Blast Man (Japan)",
	"Space Gun (World)",
	"Space Invaders '95 - Attack Of The Lunar Loonies (US)",
	"Space Invaders '95 - Attack Of The Lunar Loonies (World)",
	"Space Invaders DX (Japan F3 version)",
	"Space Invaders DX (Japan) v2.0",
	"Space Invaders DX (Japan) v2.1",
	"Space Invaders DX (US) v2.1",
	"Special Criminal Investigation (US)",
	"Special Criminal Investigation (World set 1)",
	"Special Criminal Investigation (World set 2)",
	"Super Chase - Criminal Termination (US)",
	"Super Cup Finals (World)",
	"Super Space Invaders '91 (World)",
	"Superman",
	"Superman (Japan)",
	"Syvalion (Japan)",
	"Taito Cup Finals (World)",
	"Taito Power Goal (World)",
	"The Ninja Kids (Japan)",
	"The Ninja Kids (World)",
	"The Ninja Warriors (Japan)",
	"The Ninja Warriors (World)",
	"Thunder Fox (Japan)",
	"Thunder Fox (US)",
	"Thunder Fox (World)",
	"Top Landing (World)",
	"Top Ranking Stars (Japan new version)",
	"Top Ranking Stars (Japan old version)",
	"Top Ranking Stars (World new version)",
	"Top Ranking Stars (World old version)",
	"Top Speed (US)",
	"Top Speed (World)",
	"Twin Cobra 2 (US)",
	"Twin Cobra 2 (World)",
	"Twin Hawk (US)",
	"Twin Hawk (World)",
	"Twin Qix (US Prototype)",
	"Under Fire (Japan)",
	"Under Fire (US)",
	"Under Fire (World)",
	"Violence Fight (US)",
	"Violence Fight (World)",
	"Volfied (Japan)",
	"Volfied (US)",
	"Volfied (World)",
	"Warrior Blade - Rastan Saga Episode III (Japan)",
	"World Grand Prix (Japan)",
	"World Grand Prix (joystick version set 1) (Japan)",
	"World Grand Prix (joystick version set 2) (Japan)",
	"World Grand Prix (US)",
	"World Grand Prix 2 (Japan)",
	"Yes/No Sinri Tokimeki Chart",
	"Yuuyu no Quiz de GO!GO! (Japan)",
	},
	{ --TECHNOS
	"Acrobatic Dog-Fight",
	"Battle Lane! Vol. 5 (set 1)",
	"Battle Lane! Vol. 5 (set 2)",
	"Battle Lane! Vol. 5 (set 3)",
	"Block Out (Japan)",
	"Block Out (set 1)",
	"Block Out (set 2)",
	"Bogey Manor",
	"China Gate (US)",
	"Dog-Fight (Japan)",
	"Dommy",
	"Double Dragon (Japan)",
	"Double Dragon (PlayChoice-10)",
	"Double Dragon (US)",
	"Double Dragon (World)",
	"Double Dragon 3 - The Rosetta Stone (US)",
	"Double Dragon II - The Revenge (US)",
	"Double Dragon II - The Revenge (World)",
	"Eggs",
	"Exciting Hour",
	"Hyper Duel (Japan set 1)",
	"Hyper Duel (Japan set 2)",
	"Mania Challenge (set 1)",
	"Mania Challenge (set 2)",
	"Mat Mania",
	"Minky Monkey",
	"Mysterious Stones - Dr. John's Adventure",
	"Mysterious Stones - Dr. Kick in Adventure",
	"Nekketsu Kouha Kunio-kun (Japan)",
	"Nekketsu Koukou Dodgeball Bu (Japan bootleg)",
	"Nintendo World Cup (PlayChoice-10)",
	"Renegade (US)",
	"Sai Yu Gou Ma Roku (Japan)",
	"Scrambled Egg",
	"Shadow Force (US Version 2)",
	"Solar-Warrior",
	"Super Dodge Ball (US)",
	"Syusse Oozumou (Japan)",
	"Tag Team Wrestling",
	"The Big Pro Wrestling!",
	"The Combatribes (US)",
	"U.S. Championship V'ball (Japan)",
	"U.S. Championship V'ball (set 1)",
	"WWF Superstars (US)",
	"WWF WrestleFest (Japan)",
	"WWF WrestleFest (US set 1)",
	"WWF WrestleFest (US Tecmo)",
	"Xain'd Sleena",
	},
	{ --UNIVERSAL
	"Capitol",
	"Cheeky Mouse",
	"Cosmic Alien",
	"Cosmic Alien (older)",
	"Cosmic Avenger",
	"Cosmic Guerilla",
	"Cosmic Monsters",
	"Cosmic Monsters 2",
	"Devil Zone",
	"Devil Zone (easier)",
	"Do! Run Run (Do's Castle hardware)",
	"Do! Run Run (set 1)",
	"Do! Run Run (set 2)",
	"Galaxy Wars (Universal set 1)",
	"Galaxy Wars (Universal set 2)",
	"Indoor Soccer",
	"Jumping Jack",
	"Kick Rider",
	"Lady Bug",
	"Magical Spot",
	"Magical Spot II",
	"Mighty Monkey",
	"Mr. Do vs. Unicorns",
	"Mr. Do!",
	"Mr. Do! (bugfixed)",
	"Mr. Do! (prototype)",
	"Mr. Do! (Taito)",
	"Mr. Do's Castle (older)",
	"Mr. Do's Castle (set 1)",
	"Mr. Do's Castle (set 2)",
	"Mr. Do's Wild Ride",
	"No Man's Land",
	"No Man's Land (Gottlieb)",
	"Snap Jack",
	"Space Panic (German)",
	"Space Panic (harder)",
	"Space Panic (set 2)",
	"Space Panic (set 3)",
	"Space Panic (version E)",
	"Space Raider",
	"Super Pierrot (Japan)",
	"Zero Hour",
	},
	{ --UPL
	"Acrobat Mission",
	"Ark Area",
	"Atomic Robo-kid",
	"Atomic Robo-kid (Japan)",
	"Bio-ship Paladin",
	"Black Heart",
	"Black Heart (Japan)",
	"Koutetsu Yousai Strahl (Japan set 1)",
	"Koutetsu Yousai Strahl (Japan set 2)",
	"Mouser",
	"Mouser (Cosmos)",
	"Mutant Night",
	"Ninja-Kid II (set 1)",
	"Ninja-Kid II (set 2)",
	"Ninja-Kid II (set 3)",
	"Ninjakun Majou no Bouken",
	"Nova 2001 (Japan)",
	"Nova 2001 (US)",
	"Omega Fighter",
	"Omega Fighter Special",
	"Penguin-Kun Wars (Japan)",
	"Penguin-Kun Wars (US)",
	"Rad Action",
	"Raiders5",
	"Raiders5 (Japan)",
	"Task Force Harrier",
	"Task Force Harrier (Japan)",
	"Urashima Mahjong",
	"US AAF Mustang (Japan)",
	"US AAF Mustang (Seoul Trading)",
	"Vandyke (Jaleco)",
	"Vandyke (Japan)",
	"XX Mission",
	},
}

return table[index]
end

return { getGameList = getGameList }