name: pspMAME

on:
  push:
    branches: [ conservative ]
  pull_request:
    branches: [ conservative ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  PSP:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add bash cmake git gmp mpc1 mpfr4 make
      - run: |
          git config --global --add safe.directory /__w/pspMAME097-repuken2/pspMAME097-repuken2
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          git submodule update --init --recursive --remote 
          # make all
          # mkdir obj/drivers
          # mv -v obj/mame/*.a obj/drivers
          make TARGET=simpsons
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pspMAME
          path: |
            EBOOT.PBP
